INSERT INTO `rule_lu_lookup` (`rule_lu_type`, `rule_lu_value`, `rule_lu_text`, rule_lu_component_value,
`rule_lu_status`, `rule_lu_valid`, `rule_create_user_id`, `rule_lu_create_date`, `rule_lu_last_updated_user_id`, `rule_lu_last_updated_date`) VALUES
	('HSBANK', '002', '中国工商银行', 'ICBC', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now()),
	('HSBANK', '003', '中国农业银行', 'ABC', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now()),
	('HSBANK', '004', '中国银行', 'BOC', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now()),
	('HSBANK', '005', '中国建设银行', 'CCB', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now()),
	('HSBANK', '006', '中国交通银行', 'COMM', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now()),
	('HSBANK', '007', '招商银行', 'CMB', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now()),
	('HSBANK', '009', '中国光大银行', 'CEB', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now()),
	('HSBANK', '010', '浦东发展银行', 'SPDB', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now()),
	('HSBANK', '011', '兴业银行', 'CIB', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now()),
	('HSBANK', '012', '华夏银行', 'HXBANK', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now()),
	('HSBANK', '014', '中国民生银行', 'CMBC', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now()),
	('HSBANK', '015', '中信实业银行', 'CITIC', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now()),
	('HSBANK', '016', '广东发展银行', 'GDB', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now()),
	('HSBANK', '026', '浙江省农村信用社', 'ZJNX', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now()),
	('HSBANK', '911', '杭州银行', 'HZCB', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now()),
	('HSBANK', '920', '平安银行', 'SPABANK', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now()),
	('HSBANK', '922', '北京银行', 'BJBANK', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now()),
	('HSBANK', '934', '邮政储蓄银行', 'PSBC', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now()),
	('HSBANK', '938', '渤海银行', 'BOHAIB', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now()),
	('HSBANK', '017', '上海银行', 'SHBANK', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now()),
	
	('EPAYBANK', 'ICBC', '中国工商银行', '', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now()),
	('EPAYBANK', 'ABC', '中国农业银行', '', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now()),
	('EPAYBANK', 'BOC', '中国银行', '', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now()),
	('EPAYBANK', 'CCB', '中国建设银行', '', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now()),
	('EPAYBANK', 'COMM', '中国交通银行', '', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now()),
	('EPAYBANK', 'CMB', '招商银行', '', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now()),
	('EPAYBANK', 'CEB', '中国光大银行', '', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now()),
	('EPAYBANK', 'SPDB', '浦东发展银行', '', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now()),
	('EPAYBANK', 'CIB', '兴业银行', '', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now()),
	('EPAYBANK', 'HXBANK', '华夏银行', '', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now()),	
	('EPAYBANK', 'CITIC', '中信实业银行', '', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now()),
	('EPAYBANK', 'GDB', '广东发展银行', '', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now()),	
	('EPAYBANK', 'SPABANK', '平安银行', '', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now()),	
	('EPAYBANK', 'PSBC', '邮政储蓄银行', '', NULL, b'1', 'SYSTEM', now(), 'SYSTEM', now());
