package com.codi.fundData.domain;

import java.math.BigDecimal;
import java.util.Date;

import com.codi.base.domain.BaseDomain;

/**
 * 货币基金收益表现
 * 
 * @author shi.pengyan
 * @date 2016年9月23日 下午2:04:01
 */
public class FundMMYieldPerformance extends BaseDomain {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.ID
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private Long ID;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.InnerCode
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private Integer InnerCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.TradingDay
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private Date TradingDay;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.UnitNV
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private BigDecimal UnitNV;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.AccumulatedUnitNV
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private BigDecimal AccumulatedUnitNV;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.DailyProfit
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private BigDecimal DailyProfit;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.LatestWeeklyYield
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private BigDecimal LatestWeeklyYield;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.InvolvedDays
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private Integer InvolvedDays;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.AnnualizedRRInSingleWeek
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private BigDecimal AnnualizedRRInSingleWeek;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.AnnualizedRRInTwoWeek
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private BigDecimal AnnualizedRRInTwoWeek;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.AnnualizedRRInThreeWeek
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private BigDecimal AnnualizedRRInThreeWeek;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.AnnualizedRRInFourWeek
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private BigDecimal AnnualizedRRInFourWeek;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.AnnualizedRRInFiveWeek
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private BigDecimal AnnualizedRRInFiveWeek;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.RRInThisWeek
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private BigDecimal RRInThisWeek;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.RRInSingleWeek
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private BigDecimal RRInSingleWeek;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.RRInThisMonth
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private BigDecimal RRInThisMonth;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.RRInSingleMonth
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private BigDecimal RRInSingleMonth;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.RRInThreeMonth
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private BigDecimal RRInThreeMonth;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.RRInSixMonth
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private BigDecimal RRInSixMonth;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.RRSinceThisYear
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private BigDecimal RRSinceThisYear;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.RRInSingleYear
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private BigDecimal RRInSingleYear;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.RRInTwoYear
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private BigDecimal RRInTwoYear;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.AnnualizedRRInTwoYear
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private BigDecimal AnnualizedRRInTwoYear;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.RRInThreeYear
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private BigDecimal RRInThreeYear;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.AnnualizedRRInThreeYear
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private BigDecimal AnnualizedRRInThreeYear;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.RRInFiveYear
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private BigDecimal RRInFiveYear;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.AnnualizedRRInFiveYear
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private BigDecimal AnnualizedRRInFiveYear;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.RRInTenYear
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private BigDecimal RRInTenYear;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.AnnualizedRRInTenYear
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private BigDecimal AnnualizedRRInTenYear;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.RRSinceStart
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private BigDecimal RRSinceStart;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.AnnualizedRRSinceStart
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private BigDecimal AnnualizedRRSinceStart;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.UpdateTime
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private Date UpdateTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.JSID
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private Long JSID;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_MMYieldPerformance.DailyProfit1
     *
     * @mbggenerated Fri Sep 23 14:01:09 CST 2016
     */
    private BigDecimal DailyProfit1;

    public Long getID() {
        return ID;
    }

    public void setID(Long iD) {
        ID = iD;
    }

    public Integer getInnerCode() {
        return InnerCode;
    }

    public void setInnerCode(Integer innerCode) {
        InnerCode = innerCode;
    }

    public Date getTradingDay() {
        return TradingDay;
    }

    public void setTradingDay(Date tradingDay) {
        TradingDay = tradingDay;
    }

    public BigDecimal getUnitNV() {
        return UnitNV;
    }

    public void setUnitNV(BigDecimal unitNV) {
        UnitNV = unitNV;
    }

    public BigDecimal getAccumulatedUnitNV() {
        return AccumulatedUnitNV;
    }

    public void setAccumulatedUnitNV(BigDecimal accumulatedUnitNV) {
        AccumulatedUnitNV = accumulatedUnitNV;
    }

    public BigDecimal getDailyProfit() {
        return DailyProfit;
    }

    public void setDailyProfit(BigDecimal dailyProfit) {
        DailyProfit = dailyProfit;
    }

    public BigDecimal getLatestWeeklyYield() {
        return LatestWeeklyYield;
    }

    public void setLatestWeeklyYield(BigDecimal latestWeeklyYield) {
        LatestWeeklyYield = latestWeeklyYield;
    }

    public Integer getInvolvedDays() {
        return InvolvedDays;
    }

    public void setInvolvedDays(Integer involvedDays) {
        InvolvedDays = involvedDays;
    }

    public BigDecimal getAnnualizedRRInSingleWeek() {
        return AnnualizedRRInSingleWeek;
    }

    public void setAnnualizedRRInSingleWeek(BigDecimal annualizedRRInSingleWeek) {
        AnnualizedRRInSingleWeek = annualizedRRInSingleWeek;
    }

    public BigDecimal getAnnualizedRRInTwoWeek() {
        return AnnualizedRRInTwoWeek;
    }

    public void setAnnualizedRRInTwoWeek(BigDecimal annualizedRRInTwoWeek) {
        AnnualizedRRInTwoWeek = annualizedRRInTwoWeek;
    }

    public BigDecimal getAnnualizedRRInThreeWeek() {
        return AnnualizedRRInThreeWeek;
    }

    public void setAnnualizedRRInThreeWeek(BigDecimal annualizedRRInThreeWeek) {
        AnnualizedRRInThreeWeek = annualizedRRInThreeWeek;
    }

    public BigDecimal getAnnualizedRRInFourWeek() {
        return AnnualizedRRInFourWeek;
    }

    public void setAnnualizedRRInFourWeek(BigDecimal annualizedRRInFourWeek) {
        AnnualizedRRInFourWeek = annualizedRRInFourWeek;
    }

    public BigDecimal getAnnualizedRRInFiveWeek() {
        return AnnualizedRRInFiveWeek;
    }

    public void setAnnualizedRRInFiveWeek(BigDecimal annualizedRRInFiveWeek) {
        AnnualizedRRInFiveWeek = annualizedRRInFiveWeek;
    }

    public BigDecimal getRRInThisWeek() {
        return RRInThisWeek;
    }

    public void setRRInThisWeek(BigDecimal rRInThisWeek) {
        RRInThisWeek = rRInThisWeek;
    }

    public BigDecimal getRRInSingleWeek() {
        return RRInSingleWeek;
    }

    public void setRRInSingleWeek(BigDecimal rRInSingleWeek) {
        RRInSingleWeek = rRInSingleWeek;
    }

    public BigDecimal getRRInThisMonth() {
        return RRInThisMonth;
    }

    public void setRRInThisMonth(BigDecimal rRInThisMonth) {
        RRInThisMonth = rRInThisMonth;
    }

    public BigDecimal getRRInSingleMonth() {
        return RRInSingleMonth;
    }

    public void setRRInSingleMonth(BigDecimal rRInSingleMonth) {
        RRInSingleMonth = rRInSingleMonth;
    }

    public BigDecimal getRRInThreeMonth() {
        return RRInThreeMonth;
    }

    public void setRRInThreeMonth(BigDecimal rRInThreeMonth) {
        RRInThreeMonth = rRInThreeMonth;
    }

    public BigDecimal getRRInSixMonth() {
        return RRInSixMonth;
    }

    public void setRRInSixMonth(BigDecimal rRInSixMonth) {
        RRInSixMonth = rRInSixMonth;
    }

    public BigDecimal getRRSinceThisYear() {
        return RRSinceThisYear;
    }

    public void setRRSinceThisYear(BigDecimal rRSinceThisYear) {
        RRSinceThisYear = rRSinceThisYear;
    }

    public BigDecimal getRRInSingleYear() {
        return RRInSingleYear;
    }

    public void setRRInSingleYear(BigDecimal rRInSingleYear) {
        RRInSingleYear = rRInSingleYear;
    }

    public BigDecimal getRRInTwoYear() {
        return RRInTwoYear;
    }

    public void setRRInTwoYear(BigDecimal rRInTwoYear) {
        RRInTwoYear = rRInTwoYear;
    }

    public BigDecimal getAnnualizedRRInTwoYear() {
        return AnnualizedRRInTwoYear;
    }

    public void setAnnualizedRRInTwoYear(BigDecimal annualizedRRInTwoYear) {
        AnnualizedRRInTwoYear = annualizedRRInTwoYear;
    }

    public BigDecimal getRRInThreeYear() {
        return RRInThreeYear;
    }

    public void setRRInThreeYear(BigDecimal rRInThreeYear) {
        RRInThreeYear = rRInThreeYear;
    }

    public BigDecimal getAnnualizedRRInThreeYear() {
        return AnnualizedRRInThreeYear;
    }

    public void setAnnualizedRRInThreeYear(BigDecimal annualizedRRInThreeYear) {
        AnnualizedRRInThreeYear = annualizedRRInThreeYear;
    }

    public BigDecimal getRRInFiveYear() {
        return RRInFiveYear;
    }

    public void setRRInFiveYear(BigDecimal rRInFiveYear) {
        RRInFiveYear = rRInFiveYear;
    }

    public BigDecimal getAnnualizedRRInFiveYear() {
        return AnnualizedRRInFiveYear;
    }

    public void setAnnualizedRRInFiveYear(BigDecimal annualizedRRInFiveYear) {
        AnnualizedRRInFiveYear = annualizedRRInFiveYear;
    }

    public BigDecimal getRRInTenYear() {
        return RRInTenYear;
    }

    public void setRRInTenYear(BigDecimal rRInTenYear) {
        RRInTenYear = rRInTenYear;
    }

    public BigDecimal getAnnualizedRRInTenYear() {
        return AnnualizedRRInTenYear;
    }

    public void setAnnualizedRRInTenYear(BigDecimal annualizedRRInTenYear) {
        AnnualizedRRInTenYear = annualizedRRInTenYear;
    }

    public BigDecimal getRRSinceStart() {
        return RRSinceStart;
    }

    public void setRRSinceStart(BigDecimal rRSinceStart) {
        RRSinceStart = rRSinceStart;
    }

    public BigDecimal getAnnualizedRRSinceStart() {
        return AnnualizedRRSinceStart;
    }

    public void setAnnualizedRRSinceStart(BigDecimal annualizedRRSinceStart) {
        AnnualizedRRSinceStart = annualizedRRSinceStart;
    }

    public Date getUpdateTime() {
        return UpdateTime;
    }

    public void setUpdateTime(Date updateTime) {
        UpdateTime = updateTime;
    }

    public Long getJSID() {
        return JSID;
    }

    public void setJSID(Long jSID) {
        JSID = jSID;
    }

    public BigDecimal getDailyProfit1() {
        return DailyProfit1;
    }

    public void setDailyProfit1(BigDecimal dailyProfit1) {
        DailyProfit1 = dailyProfit1;
    }

}