package com.codi.fundData.domain;

import java.util.Date;

import com.codi.base.domain.BaseDomain;

/**
 * 基金代码关联表（新）<br/>
 * 本表收录同一基金的分级关联代码、复制型基金的关联代码、封转开基金代码对应关系、基金与其收益线对应关系等信息。<br/>
 * 
 * @author shi.pengyan
 * @date 2016年11月23日 上午9:46:10
 */
public class FundCodeRelationship extends BaseDomain {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_CodeRelationshipNew.ID
     *
     * @mbggenerated Wed Nov 23 09:42:45 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_CodeRelationshipNew.InnerCode
     *
     * @mbggenerated Wed Nov 23 09:42:45 CST 2016
     */
    private Integer innercode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_CodeRelationshipNew.CodeDefine
     *
     * @mbggenerated Wed Nov 23 09:42:45 CST 2016
     */
    private Integer codedefine;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_CodeRelationshipNew.RelatedInnerCode
     *
     * @mbggenerated Wed Nov 23 09:42:45 CST 2016
     */
    private Integer relatedinnercode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_CodeRelationshipNew.RelatedCode
     *
     * @mbggenerated Wed Nov 23 09:42:45 CST 2016
     */
    private String relatedcode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_CodeRelationshipNew.StartDate
     *
     * @mbggenerated Wed Nov 23 09:42:45 CST 2016
     */
    private Date startdate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_CodeRelationshipNew.EndDate
     *
     * @mbggenerated Wed Nov 23 09:42:45 CST 2016
     */
    private Date enddate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_CodeRelationshipNew.IfEffected
     *
     * @mbggenerated Wed Nov 23 09:42:45 CST 2016
     */
    private Integer ifeffected;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_CodeRelationshipNew.Remarks
     *
     * @mbggenerated Wed Nov 23 09:42:45 CST 2016
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_CodeRelationshipNew.UpdateTime
     *
     * @mbggenerated Wed Nov 23 09:42:45 CST 2016
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_CodeRelationshipNew.JSID
     *
     * @mbggenerated Wed Nov 23 09:42:45 CST 2016
     */
    private Long jsid;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_CodeRelationshipNew.ID
     *
     * @return the value of MF_CodeRelationshipNew.ID
     *
     * @mbggenerated Wed Nov 23 09:42:45 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_CodeRelationshipNew.ID
     *
     * @param id
     *            the value for MF_CodeRelationshipNew.ID
     *
     * @mbggenerated Wed Nov 23 09:42:45 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_CodeRelationshipNew.InnerCode
     *
     * @return the value of MF_CodeRelationshipNew.InnerCode
     *
     * @mbggenerated Wed Nov 23 09:42:45 CST 2016
     */
    public Integer getInnercode() {
        return innercode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_CodeRelationshipNew.InnerCode
     *
     * @param innercode
     *            the value for MF_CodeRelationshipNew.InnerCode
     *
     * @mbggenerated Wed Nov 23 09:42:45 CST 2016
     */
    public void setInnercode(Integer innercode) {
        this.innercode = innercode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_CodeRelationshipNew.CodeDefine
     *
     * @return the value of MF_CodeRelationshipNew.CodeDefine
     *
     * @mbggenerated Wed Nov 23 09:42:45 CST 2016
     */
    public Integer getCodedefine() {
        return codedefine;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_CodeRelationshipNew.CodeDefine
     *
     * @param codedefine
     *            the value for MF_CodeRelationshipNew.CodeDefine
     *
     * @mbggenerated Wed Nov 23 09:42:45 CST 2016
     */
    public void setCodedefine(Integer codedefine) {
        this.codedefine = codedefine;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_CodeRelationshipNew.RelatedInnerCode
     *
     * @return the value of MF_CodeRelationshipNew.RelatedInnerCode
     *
     * @mbggenerated Wed Nov 23 09:42:45 CST 2016
     */
    public Integer getRelatedinnercode() {
        return relatedinnercode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_CodeRelationshipNew.RelatedInnerCode
     *
     * @param relatedinnercode
     *            the value for MF_CodeRelationshipNew.RelatedInnerCode
     *
     * @mbggenerated Wed Nov 23 09:42:45 CST 2016
     */
    public void setRelatedinnercode(Integer relatedinnercode) {
        this.relatedinnercode = relatedinnercode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_CodeRelationshipNew.RelatedCode
     *
     * @return the value of MF_CodeRelationshipNew.RelatedCode
     *
     * @mbggenerated Wed Nov 23 09:42:45 CST 2016
     */
    public String getRelatedcode() {
        return relatedcode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_CodeRelationshipNew.RelatedCode
     *
     * @param relatedcode
     *            the value for MF_CodeRelationshipNew.RelatedCode
     *
     * @mbggenerated Wed Nov 23 09:42:45 CST 2016
     */
    public void setRelatedcode(String relatedcode) {
        this.relatedcode = relatedcode == null ? null : relatedcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_CodeRelationshipNew.StartDate
     *
     * @return the value of MF_CodeRelationshipNew.StartDate
     *
     * @mbggenerated Wed Nov 23 09:42:45 CST 2016
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_CodeRelationshipNew.StartDate
     *
     * @param startdate
     *            the value for MF_CodeRelationshipNew.StartDate
     *
     * @mbggenerated Wed Nov 23 09:42:45 CST 2016
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_CodeRelationshipNew.EndDate
     *
     * @return the value of MF_CodeRelationshipNew.EndDate
     *
     * @mbggenerated Wed Nov 23 09:42:45 CST 2016
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_CodeRelationshipNew.EndDate
     *
     * @param enddate
     *            the value for MF_CodeRelationshipNew.EndDate
     *
     * @mbggenerated Wed Nov 23 09:42:45 CST 2016
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_CodeRelationshipNew.IfEffected
     *
     * @return the value of MF_CodeRelationshipNew.IfEffected
     *
     * @mbggenerated Wed Nov 23 09:42:45 CST 2016
     */
    public Integer getIfeffected() {
        return ifeffected;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_CodeRelationshipNew.IfEffected
     *
     * @param ifeffected
     *            the value for MF_CodeRelationshipNew.IfEffected
     *
     * @mbggenerated Wed Nov 23 09:42:45 CST 2016
     */
    public void setIfeffected(Integer ifeffected) {
        this.ifeffected = ifeffected;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_CodeRelationshipNew.Remarks
     *
     * @return the value of MF_CodeRelationshipNew.Remarks
     *
     * @mbggenerated Wed Nov 23 09:42:45 CST 2016
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_CodeRelationshipNew.Remarks
     *
     * @param remarks
     *            the value for MF_CodeRelationshipNew.Remarks
     *
     * @mbggenerated Wed Nov 23 09:42:45 CST 2016
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_CodeRelationshipNew.UpdateTime
     *
     * @return the value of MF_CodeRelationshipNew.UpdateTime
     *
     * @mbggenerated Wed Nov 23 09:42:45 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_CodeRelationshipNew.UpdateTime
     *
     * @param updatetime
     *            the value for MF_CodeRelationshipNew.UpdateTime
     *
     * @mbggenerated Wed Nov 23 09:42:45 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_CodeRelationshipNew.JSID
     *
     * @return the value of MF_CodeRelationshipNew.JSID
     *
     * @mbggenerated Wed Nov 23 09:42:45 CST 2016
     */
    public Long getJsid() {
        return jsid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_CodeRelationshipNew.JSID
     *
     * @param jsid
     *            the value for MF_CodeRelationshipNew.JSID
     *
     * @mbggenerated Wed Nov 23 09:42:45 CST 2016
     */
    public void setJsid(Long jsid) {
        this.jsid = jsid;
    }
}