package com.codi.fundData.domain;

import java.math.BigDecimal;
import java.util.Date;

import com.codi.base.domain.BaseDomain;

/**
 * 基金拆分
 * 
 * @author shi.pengyan
 * @date 2016年10月11日 上午10:26:43
 */
public class FundSharesSplit extends BaseDomain {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_SharesSplit.ID
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    private Long ID;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_SharesSplit.InnerCode
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    private Integer innerCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_SharesSplit.InfoPublDate
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    private Date infoPublDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_SharesSplit.InfoSource
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    private String infoSource;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_SharesSplit.InfoType
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    private Integer infoType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_SharesSplit.SplitDay
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    private Date splitDay;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_SharesSplit.SplitRatio
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    private BigDecimal splitRatio;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_SharesSplit.OutcomeNoticeIssueDate
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    private Date outcomeNoticeIssueDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_SharesSplit.ChangeRegDate
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    private Date changeRegDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_SharesSplit.NV
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    private BigDecimal NV;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_SharesSplit.SharesBefore
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    private BigDecimal sharesBefore;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_SharesSplit.SharesAfter
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    private BigDecimal sharesAfter;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_SharesSplit.UnitNVBefore
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    private BigDecimal unitNVBefore;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_SharesSplit.UnitNVAfter
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    private BigDecimal unitNVAfter;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_SharesSplit.AccumulatedUnitNVBefore
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    private BigDecimal accumulatedUnitNVBefore;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_SharesSplit.AccumulatedUnitNVAfter
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    private BigDecimal accumulatedUnitNVAfter;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_SharesSplit.XGRQ
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    private Date XGRQ;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_SharesSplit.JSID
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    private Long JSID;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_SharesSplit.InnerCodeAdd
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    private Integer innerCodeAdd;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_SharesSplit.SplitRatioAdd
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    private BigDecimal splitRatioAdd;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_SharesSplit.SharesAdd
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    private BigDecimal sharesAdd;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_SharesSplit.SharesAddCombine
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    private BigDecimal sharesAddCombine;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_SharesSplit.Remark
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_SharesSplit.ID
     *
     * @return the value of MF_SharesSplit.ID
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public Long getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_SharesSplit.ID
     *
     * @param ID
     *            the value for MF_SharesSplit.ID
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public void setID(Long ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_SharesSplit.InnerCode
     *
     * @return the value of MF_SharesSplit.InnerCode
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public Integer getInnerCode() {
        return innerCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_SharesSplit.InnerCode
     *
     * @param innerCode
     *            the value for MF_SharesSplit.InnerCode
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public void setInnerCode(Integer innerCode) {
        this.innerCode = innerCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_SharesSplit.InfoPublDate
     *
     * @return the value of MF_SharesSplit.InfoPublDate
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public Date getInfoPublDate() {
        return infoPublDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_SharesSplit.InfoPublDate
     *
     * @param infoPublDate
     *            the value for MF_SharesSplit.InfoPublDate
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public void setInfoPublDate(Date infoPublDate) {
        this.infoPublDate = infoPublDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_SharesSplit.InfoSource
     *
     * @return the value of MF_SharesSplit.InfoSource
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public String getInfoSource() {
        return infoSource;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_SharesSplit.InfoSource
     *
     * @param infoSource
     *            the value for MF_SharesSplit.InfoSource
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public void setInfoSource(String infoSource) {
        this.infoSource = infoSource == null ? null : infoSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_SharesSplit.InfoType
     *
     * @return the value of MF_SharesSplit.InfoType
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public Integer getInfoType() {
        return infoType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_SharesSplit.InfoType
     *
     * @param infoType
     *            the value for MF_SharesSplit.InfoType
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public void setInfoType(Integer infoType) {
        this.infoType = infoType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_SharesSplit.SplitDay
     *
     * @return the value of MF_SharesSplit.SplitDay
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public Date getSplitDay() {
        return splitDay;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_SharesSplit.SplitDay
     *
     * @param splitDay
     *            the value for MF_SharesSplit.SplitDay
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public void setSplitDay(Date splitDay) {
        this.splitDay = splitDay;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_SharesSplit.SplitRatio
     *
     * @return the value of MF_SharesSplit.SplitRatio
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public BigDecimal getSplitRatio() {
        return splitRatio;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_SharesSplit.SplitRatio
     *
     * @param splitRatio
     *            the value for MF_SharesSplit.SplitRatio
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public void setSplitRatio(BigDecimal splitRatio) {
        this.splitRatio = splitRatio;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_SharesSplit.OutcomeNoticeIssueDate
     *
     * @return the value of MF_SharesSplit.OutcomeNoticeIssueDate
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public Date getOutcomeNoticeIssueDate() {
        return outcomeNoticeIssueDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_SharesSplit.OutcomeNoticeIssueDate
     *
     * @param outcomeNoticeIssueDate
     *            the value for MF_SharesSplit.OutcomeNoticeIssueDate
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public void setOutcomeNoticeIssueDate(Date outcomeNoticeIssueDate) {
        this.outcomeNoticeIssueDate = outcomeNoticeIssueDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_SharesSplit.ChangeRegDate
     *
     * @return the value of MF_SharesSplit.ChangeRegDate
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public Date getChangeRegDate() {
        return changeRegDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_SharesSplit.ChangeRegDate
     *
     * @param changeRegDate
     *            the value for MF_SharesSplit.ChangeRegDate
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public void setChangeRegDate(Date changeRegDate) {
        this.changeRegDate = changeRegDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_SharesSplit.NV
     *
     * @return the value of MF_SharesSplit.NV
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public BigDecimal getNV() {
        return NV;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_SharesSplit.NV
     *
     * @param NV
     *            the value for MF_SharesSplit.NV
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public void setNV(BigDecimal NV) {
        this.NV = NV;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_SharesSplit.SharesBefore
     *
     * @return the value of MF_SharesSplit.SharesBefore
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public BigDecimal getSharesBefore() {
        return sharesBefore;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_SharesSplit.SharesBefore
     *
     * @param sharesBefore
     *            the value for MF_SharesSplit.SharesBefore
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public void setSharesBefore(BigDecimal sharesBefore) {
        this.sharesBefore = sharesBefore;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_SharesSplit.SharesAfter
     *
     * @return the value of MF_SharesSplit.SharesAfter
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public BigDecimal getSharesAfter() {
        return sharesAfter;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_SharesSplit.SharesAfter
     *
     * @param sharesAfter
     *            the value for MF_SharesSplit.SharesAfter
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public void setSharesAfter(BigDecimal sharesAfter) {
        this.sharesAfter = sharesAfter;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_SharesSplit.UnitNVBefore
     *
     * @return the value of MF_SharesSplit.UnitNVBefore
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public BigDecimal getUnitNVBefore() {
        return unitNVBefore;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_SharesSplit.UnitNVBefore
     *
     * @param unitNVBefore
     *            the value for MF_SharesSplit.UnitNVBefore
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public void setUnitNVBefore(BigDecimal unitNVBefore) {
        this.unitNVBefore = unitNVBefore;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_SharesSplit.UnitNVAfter
     *
     * @return the value of MF_SharesSplit.UnitNVAfter
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public BigDecimal getUnitNVAfter() {
        return unitNVAfter;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_SharesSplit.UnitNVAfter
     *
     * @param unitNVAfter
     *            the value for MF_SharesSplit.UnitNVAfter
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public void setUnitNVAfter(BigDecimal unitNVAfter) {
        this.unitNVAfter = unitNVAfter;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_SharesSplit.AccumulatedUnitNVBefore
     *
     * @return the value of MF_SharesSplit.AccumulatedUnitNVBefore
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public BigDecimal getAccumulatedUnitNVBefore() {
        return accumulatedUnitNVBefore;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_SharesSplit.AccumulatedUnitNVBefore
     *
     * @param accumulatedUnitNVBefore
     *            the value for MF_SharesSplit.AccumulatedUnitNVBefore
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public void setAccumulatedUnitNVBefore(BigDecimal accumulatedUnitNVBefore) {
        this.accumulatedUnitNVBefore = accumulatedUnitNVBefore;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_SharesSplit.AccumulatedUnitNVAfter
     *
     * @return the value of MF_SharesSplit.AccumulatedUnitNVAfter
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public BigDecimal getAccumulatedUnitNVAfter() {
        return accumulatedUnitNVAfter;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_SharesSplit.AccumulatedUnitNVAfter
     *
     * @param accumulatedUnitNVAfter
     *            the value for MF_SharesSplit.AccumulatedUnitNVAfter
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public void setAccumulatedUnitNVAfter(BigDecimal accumulatedUnitNVAfter) {
        this.accumulatedUnitNVAfter = accumulatedUnitNVAfter;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_SharesSplit.XGRQ
     *
     * @return the value of MF_SharesSplit.XGRQ
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public Date getXGRQ() {
        return XGRQ;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_SharesSplit.XGRQ
     *
     * @param XGRQ
     *            the value for MF_SharesSplit.XGRQ
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public void setXGRQ(Date XGRQ) {
        this.XGRQ = XGRQ;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_SharesSplit.JSID
     *
     * @return the value of MF_SharesSplit.JSID
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public Long getJSID() {
        return JSID;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_SharesSplit.JSID
     *
     * @param JSID
     *            the value for MF_SharesSplit.JSID
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public void setJSID(Long JSID) {
        this.JSID = JSID;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_SharesSplit.InnerCodeAdd
     *
     * @return the value of MF_SharesSplit.InnerCodeAdd
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public Integer getInnerCodeAdd() {
        return innerCodeAdd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_SharesSplit.InnerCodeAdd
     *
     * @param innerCodeAdd
     *            the value for MF_SharesSplit.InnerCodeAdd
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public void setInnerCodeAdd(Integer innerCodeAdd) {
        this.innerCodeAdd = innerCodeAdd;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_SharesSplit.SplitRatioAdd
     *
     * @return the value of MF_SharesSplit.SplitRatioAdd
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public BigDecimal getSplitRatioAdd() {
        return splitRatioAdd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_SharesSplit.SplitRatioAdd
     *
     * @param splitRatioAdd
     *            the value for MF_SharesSplit.SplitRatioAdd
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public void setSplitRatioAdd(BigDecimal splitRatioAdd) {
        this.splitRatioAdd = splitRatioAdd;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_SharesSplit.SharesAdd
     *
     * @return the value of MF_SharesSplit.SharesAdd
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public BigDecimal getSharesAdd() {
        return sharesAdd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_SharesSplit.SharesAdd
     *
     * @param sharesAdd
     *            the value for MF_SharesSplit.SharesAdd
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public void setSharesAdd(BigDecimal sharesAdd) {
        this.sharesAdd = sharesAdd;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_SharesSplit.SharesAddCombine
     *
     * @return the value of MF_SharesSplit.SharesAddCombine
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public BigDecimal getSharesAddCombine() {
        return sharesAddCombine;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_SharesSplit.SharesAddCombine
     *
     * @param sharesAddCombine
     *            the value for MF_SharesSplit.SharesAddCombine
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public void setSharesAddCombine(BigDecimal sharesAddCombine) {
        this.sharesAddCombine = sharesAddCombine;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_SharesSplit.Remark
     *
     * @return the value of MF_SharesSplit.Remark
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_SharesSplit.Remark
     *
     * @param remark
     *            the value for MF_SharesSplit.Remark
     *
     * @mbggenerated Tue Oct 11 10:25:11 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}