package com.codi.fundData.domain;

import java.math.BigDecimal;
import java.util.Date;

import com.codi.base.domain.BaseDomain;

public class FundRating extends BaseDomain {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    private Long id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundRating.OrganizationCode
     *
     * @mbggenerated Fri Sep 23 09:54:02 CST 2016
     */
    private Integer organizationCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundRating.ReportPeriod
     *
     * @mbggenerated Fri Sep 23 09:54:02 CST 2016
     */
    private Integer reportPeriod;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundRating.InfoPublDate
     *
     * @mbggenerated Fri Sep 23 09:54:02 CST 2016
     */
    private Date infoPublDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundRating.InfoSource
     *
     * @mbggenerated Fri Sep 23 09:54:02 CST 2016
     */
    private String infoSource;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundRating.EndDate
     *
     * @mbggenerated Fri Sep 23 09:54:02 CST 2016
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundRating.FundInnerCode
     *
     * @mbggenerated Fri Sep 23 09:54:02 CST 2016
     */
    private Integer fundInnerCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundRating.InvestmentStyle
     *
     * @mbggenerated Fri Sep 23 09:54:02 CST 2016
     */
    private Integer investmentStyle;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundRating.UnitNV
     *
     * @mbggenerated Fri Sep 23 09:54:02 CST 2016
     */
    private BigDecimal unitNV;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundRating.WeeklyYield
     *
     * @mbggenerated Fri Sep 23 09:54:02 CST 2016
     */
    private BigDecimal weeklyYield;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundRating.MonthlyYield
     *
     * @mbggenerated Fri Sep 23 09:54:02 CST 2016
     */
    private BigDecimal monthlyYield;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundRating.YieldFor3Month
     *
     * @mbggenerated Fri Sep 23 09:54:02 CST 2016
     */
    private BigDecimal yieldFor3Month;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundRating.YieldFor6Month
     *
     * @mbggenerated Fri Sep 23 09:54:02 CST 2016
     */
    private BigDecimal yieldFor6Month;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundRating.YieldFor1year
     *
     * @mbggenerated Fri Sep 23 09:54:02 CST 2016
     */
    private BigDecimal yieldFor1year;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundRating.YieldFor2year
     *
     * @mbggenerated Fri Sep 23 09:54:02 CST 2016
     */
    private BigDecimal yieldFor2year;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundRating.YieldFor3year
     *
     * @mbggenerated Fri Sep 23 09:54:02 CST 2016
     */
    private BigDecimal yieldFor3year;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundRating.YieldFor5year
     *
     * @mbggenerated Fri Sep 23 09:54:02 CST 2016
     */
    private BigDecimal yieldFor5year;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundRating.YieldFor10year
     *
     * @mbggenerated Fri Sep 23 09:54:02 CST 2016
     */
    private BigDecimal yieldFor10year;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundRating.YieldForThisyear
     *
     * @mbggenerated Fri Sep 23 09:54:02 CST 2016
     */
    private BigDecimal yieldForThisyear;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundRating.YieldSinceFounded
     *
     * @mbggenerated Fri Sep 23 09:54:02 CST 2016
     */
    private BigDecimal yieldSinceFounded;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundRating.RatingPeriod
     *
     * @mbggenerated Fri Sep 23 09:54:02 CST 2016
     */
    private Integer ratingPeriod;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundRating.EndDateOfRatingPeriod
     *
     * @mbggenerated Fri Sep 23 09:54:02 CST 2016
     */
    private Date endDateOfRatingPeriod;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundRating.Stdev
     *
     * @mbggenerated Fri Sep 23 09:54:02 CST 2016
     */
    private BigDecimal stdev;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundRating.StdevEvaluation
     *
     * @mbggenerated Fri Sep 23 09:54:02 CST 2016
     */
    private Integer stdevEvaluation;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundRating.RiskFactor
     *
     * @mbggenerated Fri Sep 23 09:54:02 CST 2016
     */
    private BigDecimal riskFactor;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundRating.RiskEvaluation
     *
     * @mbggenerated Fri Sep 23 09:54:02 CST 2016
     */
    private Integer riskEvaluation;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundRating.SharpRatio
     *
     * @mbggenerated Fri Sep 23 09:54:02 CST 2016
     */
    private BigDecimal sharpRatio;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundRating.SharpRatioEvaluation
     *
     * @mbggenerated Fri Sep 23 09:54:02 CST 2016
     */
    private Integer sharpRatioEvaluation;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundRating.RatingIndicator
     *
     * @mbggenerated Fri Sep 23 09:54:02 CST 2016
     */
    private BigDecimal ratingIndicator;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundRating.StarRank
     *
     * @mbggenerated Fri Sep 23 09:54:02 CST 2016
     */
    private Integer starRank;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundRating.XGRQ
     *
     * @mbggenerated Fri Sep 23 09:54:02 CST 2016
     */
    private Date xgrq;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundRating.JSID
     *
     * @mbggenerated Fri Sep 23 09:54:02 CST 2016
     */
    private Long jsid;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getOrganizationCode() {
        return organizationCode;
    }

    public void setOrganizationCode(Integer organizationCode) {
        this.organizationCode = organizationCode;
    }

    public Integer getReportPeriod() {
        return reportPeriod;
    }

    public void setReportPeriod(Integer reportPeriod) {
        this.reportPeriod = reportPeriod;
    }

    public Date getInfoPublDate() {
        return infoPublDate;
    }

    public void setInfoPublDate(Date infoPublDate) {
        this.infoPublDate = infoPublDate;
    }

    public String getInfoSource() {
        return infoSource;
    }

    public void setInfoSource(String infoSource) {
        this.infoSource = infoSource;
    }

    public Date getEndDate() {
        return endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public Integer getFundInnerCode() {
        return fundInnerCode;
    }

    public void setFundInnerCode(Integer fundInnerCode) {
        this.fundInnerCode = fundInnerCode;
    }

    public Integer getInvestmentStyle() {
        return investmentStyle;
    }

    public void setInvestmentStyle(Integer investmentStyle) {
        this.investmentStyle = investmentStyle;
    }

    public BigDecimal getUnitNV() {
        return unitNV;
    }

    public void setUnitNV(BigDecimal unitNV) {
        this.unitNV = unitNV;
    }

    public BigDecimal getWeeklyYield() {
        return weeklyYield;
    }

    public void setWeeklyYield(BigDecimal weeklyYield) {
        this.weeklyYield = weeklyYield;
    }

    public BigDecimal getMonthlyYield() {
        return monthlyYield;
    }

    public void setMonthlyYield(BigDecimal monthlyYield) {
        this.monthlyYield = monthlyYield;
    }

    public BigDecimal getYieldFor3Month() {
        return yieldFor3Month;
    }

    public void setYieldFor3Month(BigDecimal yieldFor3Month) {
        this.yieldFor3Month = yieldFor3Month;
    }

    public BigDecimal getYieldFor6Month() {
        return yieldFor6Month;
    }

    public void setYieldFor6Month(BigDecimal yieldFor6Month) {
        this.yieldFor6Month = yieldFor6Month;
    }

    public BigDecimal getYieldFor1year() {
        return yieldFor1year;
    }

    public void setYieldFor1year(BigDecimal yieldFor1year) {
        this.yieldFor1year = yieldFor1year;
    }

    public BigDecimal getYieldFor2year() {
        return yieldFor2year;
    }

    public void setYieldFor2year(BigDecimal yieldFor2year) {
        this.yieldFor2year = yieldFor2year;
    }

    public BigDecimal getYieldFor3year() {
        return yieldFor3year;
    }

    public void setYieldFor3year(BigDecimal yieldFor3year) {
        this.yieldFor3year = yieldFor3year;
    }

    public BigDecimal getYieldFor5year() {
        return yieldFor5year;
    }

    public void setYieldFor5year(BigDecimal yieldFor5year) {
        this.yieldFor5year = yieldFor5year;
    }

    public BigDecimal getYieldFor10year() {
        return yieldFor10year;
    }

    public void setYieldFor10year(BigDecimal yieldFor10year) {
        this.yieldFor10year = yieldFor10year;
    }

    public BigDecimal getYieldForThisyear() {
        return yieldForThisyear;
    }

    public void setYieldForThisyear(BigDecimal yieldForThisyear) {
        this.yieldForThisyear = yieldForThisyear;
    }

    public BigDecimal getYieldSinceFounded() {
        return yieldSinceFounded;
    }

    public void setYieldSinceFounded(BigDecimal yieldSinceFounded) {
        this.yieldSinceFounded = yieldSinceFounded;
    }

    public Integer getRatingPeriod() {
        return ratingPeriod;
    }

    public void setRatingPeriod(Integer ratingPeriod) {
        this.ratingPeriod = ratingPeriod;
    }

    public Date getEndDateOfRatingPeriod() {
        return endDateOfRatingPeriod;
    }

    public void setEndDateOfRatingPeriod(Date endDateOfRatingPeriod) {
        this.endDateOfRatingPeriod = endDateOfRatingPeriod;
    }


    public BigDecimal getStdev() {
        return stdev;
    }

    public void setStdev(BigDecimal stdev) {
        this.stdev = stdev;
    }

    public Integer getStdevEvaluation() {
        return stdevEvaluation;
    }

    public void setStdevEvaluation(Integer stdevEvaluation) {
        this.stdevEvaluation = stdevEvaluation;
    }

    public BigDecimal getRiskFactor() {
        return riskFactor;
    }

    public void setRiskFactor(BigDecimal riskFactor) {
        this.riskFactor = riskFactor;
    }

    public Integer getRiskEvaluation() {
        return riskEvaluation;
    }

    public void setRiskEvaluation(Integer riskEvaluation) {
        this.riskEvaluation = riskEvaluation;
    }

    public BigDecimal getSharpRatio() {
        return sharpRatio;
    }

    public void setSharpRatio(BigDecimal sharpRatio) {
        this.sharpRatio = sharpRatio;
    }

    public Integer getSharpRatioEvaluation() {
        return sharpRatioEvaluation;
    }

    public void setSharpRatioEvaluation(Integer sharpRatioEvaluation) {
        this.sharpRatioEvaluation = sharpRatioEvaluation;
    }

    public BigDecimal getRatingIndicator() {
        return ratingIndicator;
    }

    public void setRatingIndicator(BigDecimal ratingIndicator) {
        this.ratingIndicator = ratingIndicator;
    }

    public Integer getStarRank() {
        return starRank;
    }

    public void setStarRank(Integer starRank) {
        this.starRank = starRank;
    }

    public Date getXgrq() {
        return xgrq;
    }

    public void setXgrq(Date xgrq) {
        this.xgrq = xgrq;
    }

    public Long getJsid() {
        return jsid;
    }

    public void setJsid(Long jsid) {
        this.jsid = jsid;
    }
}