package com.codi.fundData.domain;

import java.math.BigDecimal;
import java.util.Date;

import com.codi.base.domain.BaseDomain;

/***
 * 基金重仓股票组合<br/>
 * 基金季报公布重仓股票组合信息
 * 
 * @author shi.pengyan
 * @date 2016年10月24日 下午5:38:16
 */
public class FundKeyStockPortfolio extends BaseDomain {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_KeyStockPortfolio.ID
     *
     * @mbggenerated Mon Oct 24 17:37:27 CST 2016
     */
    private Long ID;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_KeyStockPortfolio.InnerCode
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    private Integer innerCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_KeyStockPortfolio.ReportDate
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    private Date reportDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_KeyStockPortfolio.SerialNumber
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    private Integer serialNumber;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_KeyStockPortfolio.StockInnerCode
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    private Integer stockInnerCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_KeyStockPortfolio.SharesHolding
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    private BigDecimal sharesHolding;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_KeyStockPortfolio.MarketValue
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    private BigDecimal marketValue;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_KeyStockPortfolio.RatioInNV
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    private BigDecimal ratioInNV;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_KeyStockPortfolio.InvestType
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    private Integer investType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_KeyStockPortfolio.XGRQ
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    private Date XGRQ;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_KeyStockPortfolio.JSID
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    private Long JSID;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_KeyStockPortfolio.InfoPublDate
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    private Date infoPublDate;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_KeyStockPortfolio.ID
     *
     * @return the value of MF_KeyStockPortfolio.ID
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    public Long getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_KeyStockPortfolio.ID
     *
     * @param ID
     *            the value for MF_KeyStockPortfolio.ID
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    public void setID(Long ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_KeyStockPortfolio.InnerCode
     *
     * @return the value of MF_KeyStockPortfolio.InnerCode
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    public Integer getInnerCode() {
        return innerCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_KeyStockPortfolio.InnerCode
     *
     * @param innerCode
     *            the value for MF_KeyStockPortfolio.InnerCode
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    public void setInnerCode(Integer innerCode) {
        this.innerCode = innerCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_KeyStockPortfolio.ReportDate
     *
     * @return the value of MF_KeyStockPortfolio.ReportDate
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    public Date getReportDate() {
        return reportDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_KeyStockPortfolio.ReportDate
     *
     * @param reportDate
     *            the value for MF_KeyStockPortfolio.ReportDate
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    public void setReportDate(Date reportDate) {
        this.reportDate = reportDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_KeyStockPortfolio.SerialNumber
     *
     * @return the value of MF_KeyStockPortfolio.SerialNumber
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    public Integer getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_KeyStockPortfolio.SerialNumber
     *
     * @param serialNumber
     *            the value for MF_KeyStockPortfolio.SerialNumber
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    public void setSerialNumber(Integer serialNumber) {
        this.serialNumber = serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_KeyStockPortfolio.StockInnerCode
     *
     * @return the value of MF_KeyStockPortfolio.StockInnerCode
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    public Integer getStockInnerCode() {
        return stockInnerCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_KeyStockPortfolio.StockInnerCode
     *
     * @param stockInnerCode
     *            the value for MF_KeyStockPortfolio.StockInnerCode
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    public void setStockInnerCode(Integer stockInnerCode) {
        this.stockInnerCode = stockInnerCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_KeyStockPortfolio.SharesHolding
     *
     * @return the value of MF_KeyStockPortfolio.SharesHolding
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    public BigDecimal getSharesHolding() {
        return sharesHolding;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_KeyStockPortfolio.SharesHolding
     *
     * @param sharesHolding
     *            the value for MF_KeyStockPortfolio.SharesHolding
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    public void setSharesHolding(BigDecimal sharesHolding) {
        this.sharesHolding = sharesHolding;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_KeyStockPortfolio.MarketValue
     *
     * @return the value of MF_KeyStockPortfolio.MarketValue
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    public BigDecimal getMarketValue() {
        return marketValue;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_KeyStockPortfolio.MarketValue
     *
     * @param marketValue
     *            the value for MF_KeyStockPortfolio.MarketValue
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    public void setMarketValue(BigDecimal marketValue) {
        this.marketValue = marketValue;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_KeyStockPortfolio.RatioInNV
     *
     * @return the value of MF_KeyStockPortfolio.RatioInNV
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    public BigDecimal getRatioInNV() {
        return ratioInNV;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_KeyStockPortfolio.RatioInNV
     *
     * @param ratioInNV
     *            the value for MF_KeyStockPortfolio.RatioInNV
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    public void setRatioInNV(BigDecimal ratioInNV) {
        this.ratioInNV = ratioInNV;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_KeyStockPortfolio.InvestType
     *
     * @return the value of MF_KeyStockPortfolio.InvestType
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    public Integer getInvestType() {
        return investType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_KeyStockPortfolio.InvestType
     *
     * @param investType
     *            the value for MF_KeyStockPortfolio.InvestType
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    public void setInvestType(Integer investType) {
        this.investType = investType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_KeyStockPortfolio.XGRQ
     *
     * @return the value of MF_KeyStockPortfolio.XGRQ
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    public Date getXGRQ() {
        return XGRQ;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_KeyStockPortfolio.XGRQ
     *
     * @param XGRQ
     *            the value for MF_KeyStockPortfolio.XGRQ
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    public void setXGRQ(Date XGRQ) {
        this.XGRQ = XGRQ;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_KeyStockPortfolio.JSID
     *
     * @return the value of MF_KeyStockPortfolio.JSID
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    public Long getJSID() {
        return JSID;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_KeyStockPortfolio.JSID
     *
     * @param JSID
     *            the value for MF_KeyStockPortfolio.JSID
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    public void setJSID(Long JSID) {
        this.JSID = JSID;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_KeyStockPortfolio.InfoPublDate
     *
     * @return the value of MF_KeyStockPortfolio.InfoPublDate
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    public Date getInfoPublDate() {
        return infoPublDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_KeyStockPortfolio.InfoPublDate
     *
     * @param infoPublDate
     *            the value for MF_KeyStockPortfolio.InfoPublDate
     *
     * @mbggenerated Mon Oct 24 17:37:28 CST 2016
     */
    public void setInfoPublDate(Date infoPublDate) {
        this.infoPublDate = infoPublDate;
    }
}