package com.codi.fundData.domain;

import java.util.Date;

/**
 * 基金概况附表 MF_FundArchivesAttach <br/>
 * 存放一些与基金有关的变动信息
 * 
 * @author shi.pengyan
 * @date 2016年10月14日 下午1:53:31
 */
public class FundArchivesAttach {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundArchivesAttach.ID
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    private Long ID;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundArchivesAttach.InnerCode
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    private Integer innerCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundArchivesAttach.CompanyCode
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    private Integer companyCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundArchivesAttach.InfoSource
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    private String infoSource;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundArchivesAttach.TypeCode
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    private Integer typeCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundArchivesAttach.TypeName
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundArchivesAttach.DataCode
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    private Integer dataCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundArchivesAttach.DataName
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    private String dataName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundArchivesAttach.StartDate
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundArchivesAttach.EndDate
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundArchivesAttach.Remark
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundArchivesAttach.UpdateTime
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_FundArchivesAttach.JSID
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    private Long JSID;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_FundArchivesAttach.ID
     *
     * @return the value of MF_FundArchivesAttach.ID
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    public Long getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_FundArchivesAttach.ID
     *
     * @param ID
     *            the value for MF_FundArchivesAttach.ID
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    public void setID(Long ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_FundArchivesAttach.InnerCode
     *
     * @return the value of MF_FundArchivesAttach.InnerCode
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    public Integer getInnerCode() {
        return innerCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_FundArchivesAttach.InnerCode
     *
     * @param innerCode
     *            the value for MF_FundArchivesAttach.InnerCode
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    public void setInnerCode(Integer innerCode) {
        this.innerCode = innerCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_FundArchivesAttach.CompanyCode
     *
     * @return the value of MF_FundArchivesAttach.CompanyCode
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    public Integer getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_FundArchivesAttach.CompanyCode
     *
     * @param companyCode
     *            the value for MF_FundArchivesAttach.CompanyCode
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    public void setCompanyCode(Integer companyCode) {
        this.companyCode = companyCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_FundArchivesAttach.InfoSource
     *
     * @return the value of MF_FundArchivesAttach.InfoSource
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    public String getInfoSource() {
        return infoSource;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_FundArchivesAttach.InfoSource
     *
     * @param infoSource
     *            the value for MF_FundArchivesAttach.InfoSource
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    public void setInfoSource(String infoSource) {
        this.infoSource = infoSource == null ? null : infoSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_FundArchivesAttach.TypeCode
     *
     * @return the value of MF_FundArchivesAttach.TypeCode
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    public Integer getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_FundArchivesAttach.TypeCode
     *
     * @param typeCode
     *            the value for MF_FundArchivesAttach.TypeCode
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    public void setTypeCode(Integer typeCode) {
        this.typeCode = typeCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_FundArchivesAttach.TypeName
     *
     * @return the value of MF_FundArchivesAttach.TypeName
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_FundArchivesAttach.TypeName
     *
     * @param typeName
     *            the value for MF_FundArchivesAttach.TypeName
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_FundArchivesAttach.DataCode
     *
     * @return the value of MF_FundArchivesAttach.DataCode
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    public Integer getDataCode() {
        return dataCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_FundArchivesAttach.DataCode
     *
     * @param dataCode
     *            the value for MF_FundArchivesAttach.DataCode
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    public void setDataCode(Integer dataCode) {
        this.dataCode = dataCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_FundArchivesAttach.DataName
     *
     * @return the value of MF_FundArchivesAttach.DataName
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    public String getDataName() {
        return dataName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_FundArchivesAttach.DataName
     *
     * @param dataName
     *            the value for MF_FundArchivesAttach.DataName
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    public void setDataName(String dataName) {
        this.dataName = dataName == null ? null : dataName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_FundArchivesAttach.StartDate
     *
     * @return the value of MF_FundArchivesAttach.StartDate
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_FundArchivesAttach.StartDate
     *
     * @param startDate
     *            the value for MF_FundArchivesAttach.StartDate
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_FundArchivesAttach.EndDate
     *
     * @return the value of MF_FundArchivesAttach.EndDate
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_FundArchivesAttach.EndDate
     *
     * @param endDate
     *            the value for MF_FundArchivesAttach.EndDate
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_FundArchivesAttach.Remark
     *
     * @return the value of MF_FundArchivesAttach.Remark
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_FundArchivesAttach.Remark
     *
     * @param remark
     *            the value for MF_FundArchivesAttach.Remark
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_FundArchivesAttach.UpdateTime
     *
     * @return the value of MF_FundArchivesAttach.UpdateTime
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_FundArchivesAttach.UpdateTime
     *
     * @param updateTime
     *            the value for MF_FundArchivesAttach.UpdateTime
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_FundArchivesAttach.JSID
     *
     * @return the value of MF_FundArchivesAttach.JSID
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    public Long getJSID() {
        return JSID;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_FundArchivesAttach.JSID
     *
     * @param JSID
     *            the value for MF_FundArchivesAttach.JSID
     *
     * @mbggenerated Fri Oct 14 13:52:46 CST 2016
     */
    public void setJSID(Long JSID) {
        this.JSID = JSID;
    }
}