package com.codi.fundData.domain;

import java.math.BigDecimal;
import java.util.Date;

import com.codi.base.domain.BaseDomain;

/**
 * QDII基金投资组合明细<br/>
 * 本表记录QDII基金定期报告中披露的报告期权益投资明细情况。
 * 
 * @author shi.pengyan
 * @date 2016年10月24日 下午5:46:50
 */
public class FundQDIIPortfolioDetail extends BaseDomain {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioDetail.ID
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    private Long ID;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioDetail.InnerCode
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    private Integer innerCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioDetail.InfoPublDate
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    private Date infoPublDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioDetail.ReportType
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    private Integer reportType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioDetail.InfoSource
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    private String infoSource;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioDetail.EndDate
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioDetail.InvestType
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    private Integer investType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioDetail.SerialNumber
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    private Integer serialNumber;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioDetail.SecuCode
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    private String secuCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioDetail.SecuName
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    private String secuName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioDetail.EngName
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    private String engName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioDetail.SharesHolding
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    private BigDecimal sharesHolding;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioDetail.MarketValue
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    private BigDecimal marketValue;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioDetail.RatioInNV
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    private BigDecimal ratioInNV;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioDetail.SecuMarket
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    private Integer secuMarket;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioDetail.SecuMarketDesc
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    private String secuMarketDesc;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioDetail.HomeCountry
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    private Integer homeCountry;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioDetail.HomeCountryDesc
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    private String homeCountryDesc;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioDetail.FundType
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    private Integer fundType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioDetail.FundTypeDesc
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    private String fundTypeDesc;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioDetail.OperateType
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    private Integer operateType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioDetail.OperateTypeDesc
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    private String operateTypeDesc;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioDetail.InvestAdvisorName
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    private String investAdvisorName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioDetail.FundAssetType
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    private Integer fundAssetType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioDetail.FundAssetTypeDesc
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    private String fundAssetTypeDesc;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioDetail.InvestStyle
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    private Integer investStyle;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioDetail.InvestStyleDesc
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    private String investStyleDesc;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioDetail.CodeType
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    private Integer codeType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioDetail.SecuTradeCode
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    private String secuTradeCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioDetail.SecuInnerCode
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    private Integer secuInnerCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioDetail.UpdateTime
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioDetail.JSID
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    private Long JSID;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioDetail.InvestCategory
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    private Integer investCategory;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioDetail.ID
     *
     * @return the value of MF_QDIIPortfolioDetail.ID
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public Long getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioDetail.ID
     *
     * @param ID
     *            the value for MF_QDIIPortfolioDetail.ID
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public void setID(Long ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioDetail.InnerCode
     *
     * @return the value of MF_QDIIPortfolioDetail.InnerCode
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public Integer getInnerCode() {
        return innerCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioDetail.InnerCode
     *
     * @param innerCode
     *            the value for MF_QDIIPortfolioDetail.InnerCode
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public void setInnerCode(Integer innerCode) {
        this.innerCode = innerCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioDetail.InfoPublDate
     *
     * @return the value of MF_QDIIPortfolioDetail.InfoPublDate
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public Date getInfoPublDate() {
        return infoPublDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioDetail.InfoPublDate
     *
     * @param infoPublDate
     *            the value for MF_QDIIPortfolioDetail.InfoPublDate
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public void setInfoPublDate(Date infoPublDate) {
        this.infoPublDate = infoPublDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioDetail.ReportType
     *
     * @return the value of MF_QDIIPortfolioDetail.ReportType
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public Integer getReportType() {
        return reportType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioDetail.ReportType
     *
     * @param reportType
     *            the value for MF_QDIIPortfolioDetail.ReportType
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public void setReportType(Integer reportType) {
        this.reportType = reportType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioDetail.InfoSource
     *
     * @return the value of MF_QDIIPortfolioDetail.InfoSource
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public String getInfoSource() {
        return infoSource;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioDetail.InfoSource
     *
     * @param infoSource
     *            the value for MF_QDIIPortfolioDetail.InfoSource
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public void setInfoSource(String infoSource) {
        this.infoSource = infoSource == null ? null : infoSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioDetail.EndDate
     *
     * @return the value of MF_QDIIPortfolioDetail.EndDate
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioDetail.EndDate
     *
     * @param endDate
     *            the value for MF_QDIIPortfolioDetail.EndDate
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioDetail.InvestType
     *
     * @return the value of MF_QDIIPortfolioDetail.InvestType
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public Integer getInvestType() {
        return investType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioDetail.InvestType
     *
     * @param investType
     *            the value for MF_QDIIPortfolioDetail.InvestType
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public void setInvestType(Integer investType) {
        this.investType = investType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioDetail.SerialNumber
     *
     * @return the value of MF_QDIIPortfolioDetail.SerialNumber
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public Integer getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioDetail.SerialNumber
     *
     * @param serialNumber
     *            the value for MF_QDIIPortfolioDetail.SerialNumber
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public void setSerialNumber(Integer serialNumber) {
        this.serialNumber = serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioDetail.SecuCode
     *
     * @return the value of MF_QDIIPortfolioDetail.SecuCode
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public String getSecuCode() {
        return secuCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioDetail.SecuCode
     *
     * @param secuCode
     *            the value for MF_QDIIPortfolioDetail.SecuCode
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public void setSecuCode(String secuCode) {
        this.secuCode = secuCode == null ? null : secuCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioDetail.SecuName
     *
     * @return the value of MF_QDIIPortfolioDetail.SecuName
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public String getSecuName() {
        return secuName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioDetail.SecuName
     *
     * @param secuName
     *            the value for MF_QDIIPortfolioDetail.SecuName
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public void setSecuName(String secuName) {
        this.secuName = secuName == null ? null : secuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioDetail.EngName
     *
     * @return the value of MF_QDIIPortfolioDetail.EngName
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public String getEngName() {
        return engName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioDetail.EngName
     *
     * @param engName
     *            the value for MF_QDIIPortfolioDetail.EngName
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public void setEngName(String engName) {
        this.engName = engName == null ? null : engName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioDetail.SharesHolding
     *
     * @return the value of MF_QDIIPortfolioDetail.SharesHolding
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public BigDecimal getSharesHolding() {
        return sharesHolding;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioDetail.SharesHolding
     *
     * @param sharesHolding
     *            the value for MF_QDIIPortfolioDetail.SharesHolding
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public void setSharesHolding(BigDecimal sharesHolding) {
        this.sharesHolding = sharesHolding;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioDetail.MarketValue
     *
     * @return the value of MF_QDIIPortfolioDetail.MarketValue
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public BigDecimal getMarketValue() {
        return marketValue;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioDetail.MarketValue
     *
     * @param marketValue
     *            the value for MF_QDIIPortfolioDetail.MarketValue
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public void setMarketValue(BigDecimal marketValue) {
        this.marketValue = marketValue;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioDetail.RatioInNV
     *
     * @return the value of MF_QDIIPortfolioDetail.RatioInNV
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public BigDecimal getRatioInNV() {
        return ratioInNV;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioDetail.RatioInNV
     *
     * @param ratioInNV
     *            the value for MF_QDIIPortfolioDetail.RatioInNV
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public void setRatioInNV(BigDecimal ratioInNV) {
        this.ratioInNV = ratioInNV;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioDetail.SecuMarket
     *
     * @return the value of MF_QDIIPortfolioDetail.SecuMarket
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public Integer getSecuMarket() {
        return secuMarket;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioDetail.SecuMarket
     *
     * @param secuMarket
     *            the value for MF_QDIIPortfolioDetail.SecuMarket
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public void setSecuMarket(Integer secuMarket) {
        this.secuMarket = secuMarket;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioDetail.SecuMarketDesc
     *
     * @return the value of MF_QDIIPortfolioDetail.SecuMarketDesc
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public String getSecuMarketDesc() {
        return secuMarketDesc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioDetail.SecuMarketDesc
     *
     * @param secuMarketDesc
     *            the value for MF_QDIIPortfolioDetail.SecuMarketDesc
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public void setSecuMarketDesc(String secuMarketDesc) {
        this.secuMarketDesc = secuMarketDesc == null ? null : secuMarketDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioDetail.HomeCountry
     *
     * @return the value of MF_QDIIPortfolioDetail.HomeCountry
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public Integer getHomeCountry() {
        return homeCountry;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioDetail.HomeCountry
     *
     * @param homeCountry
     *            the value for MF_QDIIPortfolioDetail.HomeCountry
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public void setHomeCountry(Integer homeCountry) {
        this.homeCountry = homeCountry;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioDetail.HomeCountryDesc
     *
     * @return the value of MF_QDIIPortfolioDetail.HomeCountryDesc
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public String getHomeCountryDesc() {
        return homeCountryDesc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioDetail.HomeCountryDesc
     *
     * @param homeCountryDesc
     *            the value for MF_QDIIPortfolioDetail.HomeCountryDesc
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public void setHomeCountryDesc(String homeCountryDesc) {
        this.homeCountryDesc = homeCountryDesc == null ? null : homeCountryDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioDetail.FundType
     *
     * @return the value of MF_QDIIPortfolioDetail.FundType
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public Integer getFundType() {
        return fundType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioDetail.FundType
     *
     * @param fundType
     *            the value for MF_QDIIPortfolioDetail.FundType
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public void setFundType(Integer fundType) {
        this.fundType = fundType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioDetail.FundTypeDesc
     *
     * @return the value of MF_QDIIPortfolioDetail.FundTypeDesc
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public String getFundTypeDesc() {
        return fundTypeDesc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioDetail.FundTypeDesc
     *
     * @param fundTypeDesc
     *            the value for MF_QDIIPortfolioDetail.FundTypeDesc
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public void setFundTypeDesc(String fundTypeDesc) {
        this.fundTypeDesc = fundTypeDesc == null ? null : fundTypeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioDetail.OperateType
     *
     * @return the value of MF_QDIIPortfolioDetail.OperateType
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public Integer getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioDetail.OperateType
     *
     * @param operateType
     *            the value for MF_QDIIPortfolioDetail.OperateType
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public void setOperateType(Integer operateType) {
        this.operateType = operateType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioDetail.OperateTypeDesc
     *
     * @return the value of MF_QDIIPortfolioDetail.OperateTypeDesc
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public String getOperateTypeDesc() {
        return operateTypeDesc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioDetail.OperateTypeDesc
     *
     * @param operateTypeDesc
     *            the value for MF_QDIIPortfolioDetail.OperateTypeDesc
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public void setOperateTypeDesc(String operateTypeDesc) {
        this.operateTypeDesc = operateTypeDesc == null ? null : operateTypeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioDetail.InvestAdvisorName
     *
     * @return the value of MF_QDIIPortfolioDetail.InvestAdvisorName
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public String getInvestAdvisorName() {
        return investAdvisorName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioDetail.InvestAdvisorName
     *
     * @param investAdvisorName
     *            the value for MF_QDIIPortfolioDetail.InvestAdvisorName
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public void setInvestAdvisorName(String investAdvisorName) {
        this.investAdvisorName = investAdvisorName == null ? null : investAdvisorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioDetail.FundAssetType
     *
     * @return the value of MF_QDIIPortfolioDetail.FundAssetType
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public Integer getFundAssetType() {
        return fundAssetType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioDetail.FundAssetType
     *
     * @param fundAssetType
     *            the value for MF_QDIIPortfolioDetail.FundAssetType
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public void setFundAssetType(Integer fundAssetType) {
        this.fundAssetType = fundAssetType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioDetail.FundAssetTypeDesc
     *
     * @return the value of MF_QDIIPortfolioDetail.FundAssetTypeDesc
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public String getFundAssetTypeDesc() {
        return fundAssetTypeDesc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioDetail.FundAssetTypeDesc
     *
     * @param fundAssetTypeDesc
     *            the value for MF_QDIIPortfolioDetail.FundAssetTypeDesc
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public void setFundAssetTypeDesc(String fundAssetTypeDesc) {
        this.fundAssetTypeDesc = fundAssetTypeDesc == null ? null : fundAssetTypeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioDetail.InvestStyle
     *
     * @return the value of MF_QDIIPortfolioDetail.InvestStyle
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public Integer getInvestStyle() {
        return investStyle;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioDetail.InvestStyle
     *
     * @param investStyle
     *            the value for MF_QDIIPortfolioDetail.InvestStyle
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public void setInvestStyle(Integer investStyle) {
        this.investStyle = investStyle;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioDetail.InvestStyleDesc
     *
     * @return the value of MF_QDIIPortfolioDetail.InvestStyleDesc
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public String getInvestStyleDesc() {
        return investStyleDesc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioDetail.InvestStyleDesc
     *
     * @param investStyleDesc
     *            the value for MF_QDIIPortfolioDetail.InvestStyleDesc
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public void setInvestStyleDesc(String investStyleDesc) {
        this.investStyleDesc = investStyleDesc == null ? null : investStyleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioDetail.CodeType
     *
     * @return the value of MF_QDIIPortfolioDetail.CodeType
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public Integer getCodeType() {
        return codeType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioDetail.CodeType
     *
     * @param codeType
     *            the value for MF_QDIIPortfolioDetail.CodeType
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public void setCodeType(Integer codeType) {
        this.codeType = codeType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioDetail.SecuTradeCode
     *
     * @return the value of MF_QDIIPortfolioDetail.SecuTradeCode
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public String getSecuTradeCode() {
        return secuTradeCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioDetail.SecuTradeCode
     *
     * @param secuTradeCode
     *            the value for MF_QDIIPortfolioDetail.SecuTradeCode
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public void setSecuTradeCode(String secuTradeCode) {
        this.secuTradeCode = secuTradeCode == null ? null : secuTradeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioDetail.SecuInnerCode
     *
     * @return the value of MF_QDIIPortfolioDetail.SecuInnerCode
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public Integer getSecuInnerCode() {
        return secuInnerCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioDetail.SecuInnerCode
     *
     * @param secuInnerCode
     *            the value for MF_QDIIPortfolioDetail.SecuInnerCode
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public void setSecuInnerCode(Integer secuInnerCode) {
        this.secuInnerCode = secuInnerCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioDetail.UpdateTime
     *
     * @return the value of MF_QDIIPortfolioDetail.UpdateTime
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioDetail.UpdateTime
     *
     * @param updateTime
     *            the value for MF_QDIIPortfolioDetail.UpdateTime
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioDetail.JSID
     *
     * @return the value of MF_QDIIPortfolioDetail.JSID
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public Long getJSID() {
        return JSID;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioDetail.JSID
     *
     * @param JSID
     *            the value for MF_QDIIPortfolioDetail.JSID
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public void setJSID(Long JSID) {
        this.JSID = JSID;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioDetail.InvestCategory
     *
     * @return the value of MF_QDIIPortfolioDetail.InvestCategory
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public Integer getInvestCategory() {
        return investCategory;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioDetail.InvestCategory
     *
     * @param investCategory
     *            the value for MF_QDIIPortfolioDetail.InvestCategory
     *
     * @mbggenerated Mon Oct 24 17:41:38 CST 2016
     */
    public void setInvestCategory(Integer investCategory) {
        this.investCategory = investCategory;
    }
}