package com.codi.fundData.domain;

import java.math.BigDecimal;
import java.util.Date;

import com.codi.base.domain.BaseDomain;

/**
 * 基金行业投资分布信息
 * 
 * @author shi.pengyan
 * @date 2016年10月25日 下午3:44:20
 */
public class FundInvestIndustry extends BaseDomain {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_InvestIndustry.ID
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    private Long ID;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_InvestIndustry.InnerCode
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    private Integer innerCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_InvestIndustry.InfoPublDate
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    private Date infoPublDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_InvestIndustry.ReportDate
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    private Date reportDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_InvestIndustry.InvestType
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    private Integer investType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_InvestIndustry.IndustryCode
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    private Integer industryCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_InvestIndustry.IndustryName
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    private String industryName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_InvestIndustry.MarketValue
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    private BigDecimal marketValue;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_InvestIndustry.RatioInNV
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    private BigDecimal ratioInNV;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_InvestIndustry.XGRQ
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    private Date XGRQ;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_InvestIndustry.JSID
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    private Long JSID;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_InvestIndustry.InduStandard
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    private Integer induStandard;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_InvestIndustry.InduDiscCode
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    private String induDiscCode;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_InvestIndustry.ID
     *
     * @return the value of MF_InvestIndustry.ID
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    public Long getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_InvestIndustry.ID
     *
     * @param ID
     *            the value for MF_InvestIndustry.ID
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    public void setID(Long ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_InvestIndustry.InnerCode
     *
     * @return the value of MF_InvestIndustry.InnerCode
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    public Integer getInnerCode() {
        return innerCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_InvestIndustry.InnerCode
     *
     * @param innerCode
     *            the value for MF_InvestIndustry.InnerCode
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    public void setInnerCode(Integer innerCode) {
        this.innerCode = innerCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_InvestIndustry.InfoPublDate
     *
     * @return the value of MF_InvestIndustry.InfoPublDate
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    public Date getInfoPublDate() {
        return infoPublDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_InvestIndustry.InfoPublDate
     *
     * @param infoPublDate
     *            the value for MF_InvestIndustry.InfoPublDate
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    public void setInfoPublDate(Date infoPublDate) {
        this.infoPublDate = infoPublDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_InvestIndustry.ReportDate
     *
     * @return the value of MF_InvestIndustry.ReportDate
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    public Date getReportDate() {
        return reportDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_InvestIndustry.ReportDate
     *
     * @param reportDate
     *            the value for MF_InvestIndustry.ReportDate
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    public void setReportDate(Date reportDate) {
        this.reportDate = reportDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_InvestIndustry.InvestType
     *
     * @return the value of MF_InvestIndustry.InvestType
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    public Integer getInvestType() {
        return investType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_InvestIndustry.InvestType
     *
     * @param investType
     *            the value for MF_InvestIndustry.InvestType
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    public void setInvestType(Integer investType) {
        this.investType = investType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_InvestIndustry.IndustryCode
     *
     * @return the value of MF_InvestIndustry.IndustryCode
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    public Integer getIndustryCode() {
        return industryCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_InvestIndustry.IndustryCode
     *
     * @param industryCode
     *            the value for MF_InvestIndustry.IndustryCode
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    public void setIndustryCode(Integer industryCode) {
        this.industryCode = industryCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_InvestIndustry.IndustryName
     *
     * @return the value of MF_InvestIndustry.IndustryName
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    public String getIndustryName() {
        return industryName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_InvestIndustry.IndustryName
     *
     * @param industryName
     *            the value for MF_InvestIndustry.IndustryName
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    public void setIndustryName(String industryName) {
        this.industryName = industryName == null ? null : industryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_InvestIndustry.MarketValue
     *
     * @return the value of MF_InvestIndustry.MarketValue
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    public BigDecimal getMarketValue() {
        return marketValue;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_InvestIndustry.MarketValue
     *
     * @param marketValue
     *            the value for MF_InvestIndustry.MarketValue
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    public void setMarketValue(BigDecimal marketValue) {
        this.marketValue = marketValue;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_InvestIndustry.RatioInNV
     *
     * @return the value of MF_InvestIndustry.RatioInNV
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    public BigDecimal getRatioInNV() {
        return ratioInNV;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_InvestIndustry.RatioInNV
     *
     * @param ratioInNV
     *            the value for MF_InvestIndustry.RatioInNV
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    public void setRatioInNV(BigDecimal ratioInNV) {
        this.ratioInNV = ratioInNV;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_InvestIndustry.XGRQ
     *
     * @return the value of MF_InvestIndustry.XGRQ
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    public Date getXGRQ() {
        return XGRQ;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_InvestIndustry.XGRQ
     *
     * @param XGRQ
     *            the value for MF_InvestIndustry.XGRQ
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    public void setXGRQ(Date XGRQ) {
        this.XGRQ = XGRQ;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_InvestIndustry.JSID
     *
     * @return the value of MF_InvestIndustry.JSID
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    public Long getJSID() {
        return JSID;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_InvestIndustry.JSID
     *
     * @param JSID
     *            the value for MF_InvestIndustry.JSID
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    public void setJSID(Long JSID) {
        this.JSID = JSID;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_InvestIndustry.InduStandard
     *
     * @return the value of MF_InvestIndustry.InduStandard
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    public Integer getInduStandard() {
        return induStandard;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_InvestIndustry.InduStandard
     *
     * @param induStandard
     *            the value for MF_InvestIndustry.InduStandard
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    public void setInduStandard(Integer induStandard) {
        this.induStandard = induStandard;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_InvestIndustry.InduDiscCode
     *
     * @return the value of MF_InvestIndustry.InduDiscCode
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    public String getInduDiscCode() {
        return induDiscCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_InvestIndustry.InduDiscCode
     *
     * @param induDiscCode
     *            the value for MF_InvestIndustry.InduDiscCode
     *
     * @mbggenerated Tue Oct 25 15:39:39 CST 2016
     */
    public void setInduDiscCode(String induDiscCode) {
        this.induDiscCode = induDiscCode == null ? null : induDiscCode.trim();
    }
}