package com.codi.fundData.domain;

import java.math.BigDecimal;
import java.util.Date;

import com.codi.base.domain.BaseDomain;

/**
 * QDII基金定期报告中披露的期末按行业分类的权益投资组合情况。
 * 
 * @author shi.pengyan
 * @date 2016年10月25日 下午3:44:55
 */
public class FundQDIIPortfolioIndustry extends BaseDomain {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioIndustry.ID
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    private Long ID;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioIndustry.InnerCode
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    private Integer innerCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioIndustry.InfoPublDate
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    private Date infoPublDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioIndustry.InfoSource
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    private String infoSource;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioIndustry.EndDate
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioIndustry.Standard
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    private Integer standard;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioIndustry.SerialNumber
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    private Integer serialNumber;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioIndustry.IndustryType
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    private Integer industryType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioIndustry.IndustryName
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    private String industryName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioIndustry.MarketValue
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    private BigDecimal marketValue;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioIndustry.RatioInNV
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    private BigDecimal ratioInNV;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioIndustry.Remark
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioIndustry.UpdateTime
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIPortfolioIndustry.JSID
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    private Long JSID;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioIndustry.ID
     *
     * @return the value of MF_QDIIPortfolioIndustry.ID
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    public Long getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioIndustry.ID
     *
     * @param ID
     *            the value for MF_QDIIPortfolioIndustry.ID
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    public void setID(Long ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioIndustry.InnerCode
     *
     * @return the value of MF_QDIIPortfolioIndustry.InnerCode
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    public Integer getInnerCode() {
        return innerCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioIndustry.InnerCode
     *
     * @param innerCode
     *            the value for MF_QDIIPortfolioIndustry.InnerCode
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    public void setInnerCode(Integer innerCode) {
        this.innerCode = innerCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioIndustry.InfoPublDate
     *
     * @return the value of MF_QDIIPortfolioIndustry.InfoPublDate
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    public Date getInfoPublDate() {
        return infoPublDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioIndustry.InfoPublDate
     *
     * @param infoPublDate
     *            the value for MF_QDIIPortfolioIndustry.InfoPublDate
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    public void setInfoPublDate(Date infoPublDate) {
        this.infoPublDate = infoPublDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioIndustry.InfoSource
     *
     * @return the value of MF_QDIIPortfolioIndustry.InfoSource
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    public String getInfoSource() {
        return infoSource;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioIndustry.InfoSource
     *
     * @param infoSource
     *            the value for MF_QDIIPortfolioIndustry.InfoSource
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    public void setInfoSource(String infoSource) {
        this.infoSource = infoSource == null ? null : infoSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioIndustry.EndDate
     *
     * @return the value of MF_QDIIPortfolioIndustry.EndDate
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioIndustry.EndDate
     *
     * @param endDate
     *            the value for MF_QDIIPortfolioIndustry.EndDate
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioIndustry.Standard
     *
     * @return the value of MF_QDIIPortfolioIndustry.Standard
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    public Integer getStandard() {
        return standard;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioIndustry.Standard
     *
     * @param standard
     *            the value for MF_QDIIPortfolioIndustry.Standard
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    public void setStandard(Integer standard) {
        this.standard = standard;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioIndustry.SerialNumber
     *
     * @return the value of MF_QDIIPortfolioIndustry.SerialNumber
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    public Integer getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioIndustry.SerialNumber
     *
     * @param serialNumber
     *            the value for MF_QDIIPortfolioIndustry.SerialNumber
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    public void setSerialNumber(Integer serialNumber) {
        this.serialNumber = serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioIndustry.IndustryType
     *
     * @return the value of MF_QDIIPortfolioIndustry.IndustryType
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    public Integer getIndustryType() {
        return industryType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioIndustry.IndustryType
     *
     * @param industryType
     *            the value for MF_QDIIPortfolioIndustry.IndustryType
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    public void setIndustryType(Integer industryType) {
        this.industryType = industryType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioIndustry.IndustryName
     *
     * @return the value of MF_QDIIPortfolioIndustry.IndustryName
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    public String getIndustryName() {
        return industryName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioIndustry.IndustryName
     *
     * @param industryName
     *            the value for MF_QDIIPortfolioIndustry.IndustryName
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    public void setIndustryName(String industryName) {
        this.industryName = industryName == null ? null : industryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioIndustry.MarketValue
     *
     * @return the value of MF_QDIIPortfolioIndustry.MarketValue
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    public BigDecimal getMarketValue() {
        return marketValue;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioIndustry.MarketValue
     *
     * @param marketValue
     *            the value for MF_QDIIPortfolioIndustry.MarketValue
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    public void setMarketValue(BigDecimal marketValue) {
        this.marketValue = marketValue;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioIndustry.RatioInNV
     *
     * @return the value of MF_QDIIPortfolioIndustry.RatioInNV
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    public BigDecimal getRatioInNV() {
        return ratioInNV;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioIndustry.RatioInNV
     *
     * @param ratioInNV
     *            the value for MF_QDIIPortfolioIndustry.RatioInNV
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    public void setRatioInNV(BigDecimal ratioInNV) {
        this.ratioInNV = ratioInNV;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioIndustry.Remark
     *
     * @return the value of MF_QDIIPortfolioIndustry.Remark
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioIndustry.Remark
     *
     * @param remark
     *            the value for MF_QDIIPortfolioIndustry.Remark
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioIndustry.UpdateTime
     *
     * @return the value of MF_QDIIPortfolioIndustry.UpdateTime
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioIndustry.UpdateTime
     *
     * @param updateTime
     *            the value for MF_QDIIPortfolioIndustry.UpdateTime
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIPortfolioIndustry.JSID
     *
     * @return the value of MF_QDIIPortfolioIndustry.JSID
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    public Long getJSID() {
        return JSID;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIPortfolioIndustry.JSID
     *
     * @param JSID
     *            the value for MF_QDIIPortfolioIndustry.JSID
     *
     * @mbggenerated Tue Oct 25 15:40:13 CST 2016
     */
    public void setJSID(Long JSID) {
        this.JSID = JSID;
    }
}