package com.codi.fundData.domain;

import java.math.BigDecimal;
import java.util.Date;

import com.codi.base.domain.BaseDomain;

/**
 * QDII基金权益投资组合_资产配置<br/>
 * 收录QDII基金定期报告中披露的基金资产大类配置情况，包括股票、债券、银行存款和清算备付金、其他资产、买入返售证券、卖出回购证券、国债及货币资金、
 * 可转换债券等
 * 
 * @author shi.pengyan
 * @date 2016年10月24日 下午5:45:29
 */
public class FundQDIIAssetAllocation extends BaseDomain {
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIAssetAllocation.ID
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    private Long ID;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIAssetAllocation.InnerCode
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    private Integer innerCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIAssetAllocation.InfoPublDate
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    private Date infoPublDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIAssetAllocation.InfoSource
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    private String infoSource;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIAssetAllocation.EndDate
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIAssetAllocation.SerialNumber
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    private Integer serialNumber;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIAssetAllocation.AssetType
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    private Integer assetType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIAssetAllocation.AssetName
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    private String assetName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIAssetAllocation.MarketValue
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    private BigDecimal marketValue;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIAssetAllocation.RatioInNV
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    private BigDecimal ratioInNV;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIAssetAllocation.Remark
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIAssetAllocation.UpdateTime
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIAssetAllocation.JSID
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    private Long JSID;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_QDIIAssetAllocation.RatioInTotalAsset
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    private BigDecimal ratioInTotalAsset;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIAssetAllocation.ID
     *
     * @return the value of MF_QDIIAssetAllocation.ID
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    public Long getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIAssetAllocation.ID
     *
     * @param ID
     *            the value for MF_QDIIAssetAllocation.ID
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    public void setID(Long ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIAssetAllocation.InnerCode
     *
     * @return the value of MF_QDIIAssetAllocation.InnerCode
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    public Integer getInnerCode() {
        return innerCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIAssetAllocation.InnerCode
     *
     * @param innerCode
     *            the value for MF_QDIIAssetAllocation.InnerCode
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    public void setInnerCode(Integer innerCode) {
        this.innerCode = innerCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIAssetAllocation.InfoPublDate
     *
     * @return the value of MF_QDIIAssetAllocation.InfoPublDate
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    public Date getInfoPublDate() {
        return infoPublDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIAssetAllocation.InfoPublDate
     *
     * @param infoPublDate
     *            the value for MF_QDIIAssetAllocation.InfoPublDate
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    public void setInfoPublDate(Date infoPublDate) {
        this.infoPublDate = infoPublDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIAssetAllocation.InfoSource
     *
     * @return the value of MF_QDIIAssetAllocation.InfoSource
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    public String getInfoSource() {
        return infoSource;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIAssetAllocation.InfoSource
     *
     * @param infoSource
     *            the value for MF_QDIIAssetAllocation.InfoSource
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    public void setInfoSource(String infoSource) {
        this.infoSource = infoSource == null ? null : infoSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIAssetAllocation.EndDate
     *
     * @return the value of MF_QDIIAssetAllocation.EndDate
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIAssetAllocation.EndDate
     *
     * @param endDate
     *            the value for MF_QDIIAssetAllocation.EndDate
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIAssetAllocation.SerialNumber
     *
     * @return the value of MF_QDIIAssetAllocation.SerialNumber
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    public Integer getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIAssetAllocation.SerialNumber
     *
     * @param serialNumber
     *            the value for MF_QDIIAssetAllocation.SerialNumber
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    public void setSerialNumber(Integer serialNumber) {
        this.serialNumber = serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIAssetAllocation.AssetType
     *
     * @return the value of MF_QDIIAssetAllocation.AssetType
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    public Integer getAssetType() {
        return assetType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIAssetAllocation.AssetType
     *
     * @param assetType
     *            the value for MF_QDIIAssetAllocation.AssetType
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    public void setAssetType(Integer assetType) {
        this.assetType = assetType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIAssetAllocation.AssetName
     *
     * @return the value of MF_QDIIAssetAllocation.AssetName
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    public String getAssetName() {
        return assetName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIAssetAllocation.AssetName
     *
     * @param assetName
     *            the value for MF_QDIIAssetAllocation.AssetName
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    public void setAssetName(String assetName) {
        this.assetName = assetName == null ? null : assetName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIAssetAllocation.MarketValue
     *
     * @return the value of MF_QDIIAssetAllocation.MarketValue
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    public BigDecimal getMarketValue() {
        return marketValue;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIAssetAllocation.MarketValue
     *
     * @param marketValue
     *            the value for MF_QDIIAssetAllocation.MarketValue
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    public void setMarketValue(BigDecimal marketValue) {
        this.marketValue = marketValue;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIAssetAllocation.RatioInNV
     *
     * @return the value of MF_QDIIAssetAllocation.RatioInNV
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    public BigDecimal getRatioInNV() {
        return ratioInNV;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIAssetAllocation.RatioInNV
     *
     * @param ratioInNV
     *            the value for MF_QDIIAssetAllocation.RatioInNV
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    public void setRatioInNV(BigDecimal ratioInNV) {
        this.ratioInNV = ratioInNV;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIAssetAllocation.Remark
     *
     * @return the value of MF_QDIIAssetAllocation.Remark
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIAssetAllocation.Remark
     *
     * @param remark
     *            the value for MF_QDIIAssetAllocation.Remark
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIAssetAllocation.UpdateTime
     *
     * @return the value of MF_QDIIAssetAllocation.UpdateTime
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIAssetAllocation.UpdateTime
     *
     * @param updateTime
     *            the value for MF_QDIIAssetAllocation.UpdateTime
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIAssetAllocation.JSID
     *
     * @return the value of MF_QDIIAssetAllocation.JSID
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    public Long getJSID() {
        return JSID;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIAssetAllocation.JSID
     *
     * @param JSID
     *            the value for MF_QDIIAssetAllocation.JSID
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    public void setJSID(Long JSID) {
        this.JSID = JSID;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_QDIIAssetAllocation.RatioInTotalAsset
     *
     * @return the value of MF_QDIIAssetAllocation.RatioInTotalAsset
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    public BigDecimal getRatioInTotalAsset() {
        return ratioInTotalAsset;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_QDIIAssetAllocation.RatioInTotalAsset
     *
     * @param ratioInTotalAsset
     *            the value for MF_QDIIAssetAllocation.RatioInTotalAsset
     *
     * @mbggenerated Mon Oct 24 17:43:04 CST 2016
     */
    public void setRatioInTotalAsset(BigDecimal ratioInTotalAsset) {
        this.ratioInTotalAsset = ratioInTotalAsset;
    }
}