package com.codi.fundData.domain;

import java.math.BigDecimal;
import java.util.Date;

import com.codi.base.domain.BaseDomain;

/**
 * 基金净值（所有数据包括历史数据）
 * 
 * @author shi.pengyan
 * @date 2016年9月22日 下午4:07:58
 */
public class FundNetValue extends BaseDomain {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_NetValue.ID
     *
     * @mbggenerated Thu Sep 22 16:06:58 CST 2016
     */
    private Long id;

    // 基金代码
    private String secuCode;
    // 中文名称
    private String chiName;
    // 中文名称缩写
    private String chiNameAbbr;
    // 证券简称
    private String secuAbbr;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_NetValue.InnerCode
     *
     * @mbggenerated Thu Sep 22 16:06:58 CST 2016
     */
    private Integer innerCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_NetValue.InfoPublDate
     *
     * @mbggenerated Thu Sep 22 16:06:58 CST 2016
     */
    private Date infoPublDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_NetValue.InfoSource
     *
     * @mbggenerated Thu Sep 22 16:06:58 CST 2016
     */
    private String infoSource;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_NetValue.EndDate
     *
     * @mbggenerated Thu Sep 22 16:06:58 CST 2016
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_NetValue.NV
     *
     * @mbggenerated Thu Sep 22 16:06:58 CST 2016
     */
    private BigDecimal nv;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_NetValue.UnitNV
     *
     * @mbggenerated Thu Sep 22 16:06:58 CST 2016
     */
    private BigDecimal unitNV;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_NetValue.AccumulatedUnitNV
     *
     * @mbggenerated Thu Sep 22 16:06:58 CST 2016
     */
    private BigDecimal accumulatedUnitNV;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_NetValue.DailyProfit
     *
     * @mbggenerated Thu Sep 22 16:06:58 CST 2016
     */
    private BigDecimal dailyProfit;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_NetValue.LatestWeeklyYield
     *
     * @mbggenerated Thu Sep 22 16:06:58 CST 2016
     */
    private BigDecimal latestWeeklyYield;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_NetValue.NVDailyGrowthRate
     *
     * @mbggenerated Thu Sep 22 16:06:58 CST 2016
     */
    private BigDecimal nvDailyGrowthRate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_NetValue.NVWeeklyGrowthRate
     *
     * @mbggenerated Thu Sep 22 16:06:58 CST 2016
     */
    private BigDecimal nvWeeklyGrowthRate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_NetValue.DiscountRatio
     *
     * @mbggenerated Thu Sep 22 16:06:58 CST 2016
     */
    private BigDecimal discountRatio;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_NetValue.XGRQ
     *
     * @mbggenerated Thu Sep 22 16:06:58 CST 2016
     */
    private Date xgrq;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_NetValue.JSID
     *
     * @mbggenerated Thu Sep 22 16:06:58 CST 2016
     */
    private Long jsid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_NetValue.InvolvedDays
     *
     * @mbggenerated Thu Sep 22 16:06:58 CST 2016
     */
    private Integer involvedDays;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getInnerCode() {
        return innerCode;
    }

    public void setInnerCode(Integer innerCode) {
        this.innerCode = innerCode;
    }

    public Date getInfoPublDate() {
        return infoPublDate;
    }

    public void setInfoPublDate(Date infoPublDate) {
        this.infoPublDate = infoPublDate;
    }

    public String getInfoSource() {
        return infoSource;
    }

    public void setInfoSource(String infoSource) {
        this.infoSource = infoSource;
    }

    public Date getEndDate() {
        return endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public BigDecimal getNv() {
        return nv;
    }

    public void setNv(BigDecimal nv) {
        this.nv = nv;
    }

    public BigDecimal getUnitNV() {
        return unitNV;
    }

    public void setUnitNV(BigDecimal unitNV) {
        this.unitNV = unitNV;
    }

    public BigDecimal getAccumulatedUnitNV() {
        return accumulatedUnitNV;
    }

    public void setAccumulatedUnitNV(BigDecimal accumulatedUnitNV) {
        this.accumulatedUnitNV = accumulatedUnitNV;
    }

    public BigDecimal getDailyProfit() {
        return dailyProfit;
    }

    public void setDailyProfit(BigDecimal dailyProfit) {
        this.dailyProfit = dailyProfit;
    }

    public BigDecimal getLatestWeeklyYield() {
        return latestWeeklyYield;
    }

    public void setLatestWeeklyYield(BigDecimal latestWeeklyYield) {
        this.latestWeeklyYield = latestWeeklyYield;
    }

    public BigDecimal getNvDailyGrowthRate() {
        return nvDailyGrowthRate;
    }

    public void setNvDailyGrowthRate(BigDecimal nvDailyGrowthRate) {
        this.nvDailyGrowthRate = nvDailyGrowthRate;
    }

    public BigDecimal getNvWeeklyGrowthRate() {
        return nvWeeklyGrowthRate;
    }

    public void setNvWeeklyGrowthRate(BigDecimal nvWeeklyGrowthRate) {
        this.nvWeeklyGrowthRate = nvWeeklyGrowthRate;
    }

    public BigDecimal getDiscountRatio() {
        return discountRatio;
    }

    public void setDiscountRatio(BigDecimal discountRatio) {
        this.discountRatio = discountRatio;
    }

    public Date getXgrq() {
        return xgrq;
    }

    public void setXgrq(Date xgrq) {
        this.xgrq = xgrq;
    }

    public Long getJsid() {
        return jsid;
    }

    public void setJsid(Long jsid) {
        this.jsid = jsid;
    }

    public Integer getInvolvedDays() {
        return involvedDays;
    }

    public void setInvolvedDays(Integer involvedDays) {
        this.involvedDays = involvedDays;
    }

    public String getChiName() {
        return chiName;
    }

    public void setChiName(String chiName) {
        this.chiName = chiName;
    }

    public String getChiNameAbbr() {
        return chiNameAbbr;
    }

    public void setChiNameAbbr(String chiNameAbbr) {
        this.chiNameAbbr = chiNameAbbr;
    }

    public String getSecuAbbr() {
        return secuAbbr;
    }

    public void setSecuAbbr(String secuAbbr) {
        this.secuAbbr = secuAbbr;
    }

    public String getSecuCode() {
        return secuCode;
    }

    public void setSecuCode(String secuCode) {
        this.secuCode = secuCode;
    }

}