package com.codi.fundData.domain;

import java.math.BigDecimal;
import java.util.Date;

import com.codi.base.domain.BaseDomain;

/**
 * 基金分红
 * 
 * @author shi.pengyan
 * @date 2016年10月11日 上午10:26:27
 */
public class FundDividend extends BaseDomain {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_Dividend.ID
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    private Long ID;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_Dividend.InnerCode
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    private Integer innerCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_Dividend.InfoPublDate
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    private Date infoPublDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_Dividend.InfoSource
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    private String infoSource;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_Dividend.EndDate
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_Dividend.UnitProfit
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    private BigDecimal unitProfit;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_Dividend.UnitRetainedProfit
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    private BigDecimal unitRetainedProfit;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_Dividend.IfDistributed
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    private Byte ifDistributed;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_Dividend.DividendRatioBeforeTax
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    private BigDecimal dividendRatioBeforeTax;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_Dividend.ActualRatioAfterTax
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    private BigDecimal actualRatioAfterTax;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_Dividend.Dividendsum
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    private BigDecimal dividendsum;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_Dividend.ReDate
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    private Date reDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_Dividend.ExRightDate
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    private Date exRightDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_Dividend.ExecuteDate
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    private Date executeDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_Dividend.SchemeModification
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    private String schemeModification;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_Dividend.XGRQ
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    private Date XGRQ;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_Dividend.JSID
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    private Long JSID;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_Dividend.ReinvestDay
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    private Date reinvestDay;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_Dividend.AccountDay
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    private Date accountDay;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_Dividend.RedemptionDay
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    private Date redemptionDay;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_Dividend.UnitProfitYTD
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    private BigDecimal unitProfitYTD;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_Dividend.DividendSumYTD
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    private BigDecimal dividendSumYTD;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_Dividend.DividendTimesYTD
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    private Integer dividendTimesYTD;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_Dividend.DiviSumSinceInception
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    private BigDecimal diviSumSinceInception;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_Dividend.DiviTimesSinceIncepion
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    private Integer diviTimesSinceIncepion;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_Dividend.EventProcedureCode
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    private Integer eventProcedureCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_Dividend.EventProcedure
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    private String eventProcedure;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_Dividend.ExRightDateEX
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    private Date exRightDateEX;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_Dividend.ExRightDateCurbEX
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    private Date exRightDateCurbEX;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_Dividend.ExecuteDateEX
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    private Date executeDateEX;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_Dividend.ExecuteDateCurbEX
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    private Date executeDateCurbEX;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_Dividend.DistributableProfits
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    private BigDecimal distributableProfits;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column MF_Dividend.AllocationValue
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    private BigDecimal allocationValue;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_Dividend.ID
     *
     * @return the value of MF_Dividend.ID
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public Long getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_Dividend.ID
     *
     * @param ID
     *            the value for MF_Dividend.ID
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public void setID(Long ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_Dividend.InnerCode
     *
     * @return the value of MF_Dividend.InnerCode
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public Integer getInnerCode() {
        return innerCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_Dividend.InnerCode
     *
     * @param innerCode
     *            the value for MF_Dividend.InnerCode
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public void setInnerCode(Integer innerCode) {
        this.innerCode = innerCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_Dividend.InfoPublDate
     *
     * @return the value of MF_Dividend.InfoPublDate
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public Date getInfoPublDate() {
        return infoPublDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_Dividend.InfoPublDate
     *
     * @param infoPublDate
     *            the value for MF_Dividend.InfoPublDate
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public void setInfoPublDate(Date infoPublDate) {
        this.infoPublDate = infoPublDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_Dividend.InfoSource
     *
     * @return the value of MF_Dividend.InfoSource
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public String getInfoSource() {
        return infoSource;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_Dividend.InfoSource
     *
     * @param infoSource
     *            the value for MF_Dividend.InfoSource
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public void setInfoSource(String infoSource) {
        this.infoSource = infoSource == null ? null : infoSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_Dividend.EndDate
     *
     * @return the value of MF_Dividend.EndDate
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_Dividend.EndDate
     *
     * @param endDate
     *            the value for MF_Dividend.EndDate
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_Dividend.UnitProfit
     *
     * @return the value of MF_Dividend.UnitProfit
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public BigDecimal getUnitProfit() {
        return unitProfit;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_Dividend.UnitProfit
     *
     * @param unitProfit
     *            the value for MF_Dividend.UnitProfit
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public void setUnitProfit(BigDecimal unitProfit) {
        this.unitProfit = unitProfit;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_Dividend.UnitRetainedProfit
     *
     * @return the value of MF_Dividend.UnitRetainedProfit
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public BigDecimal getUnitRetainedProfit() {
        return unitRetainedProfit;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_Dividend.UnitRetainedProfit
     *
     * @param unitRetainedProfit
     *            the value for MF_Dividend.UnitRetainedProfit
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public void setUnitRetainedProfit(BigDecimal unitRetainedProfit) {
        this.unitRetainedProfit = unitRetainedProfit;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_Dividend.IfDistributed
     *
     * @return the value of MF_Dividend.IfDistributed
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public Byte getIfDistributed() {
        return ifDistributed;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_Dividend.IfDistributed
     *
     * @param ifDistributed
     *            the value for MF_Dividend.IfDistributed
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public void setIfDistributed(Byte ifDistributed) {
        this.ifDistributed = ifDistributed;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_Dividend.DividendRatioBeforeTax
     *
     * @return the value of MF_Dividend.DividendRatioBeforeTax
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public BigDecimal getDividendRatioBeforeTax() {
        return dividendRatioBeforeTax;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_Dividend.DividendRatioBeforeTax
     *
     * @param dividendRatioBeforeTax
     *            the value for MF_Dividend.DividendRatioBeforeTax
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public void setDividendRatioBeforeTax(BigDecimal dividendRatioBeforeTax) {
        this.dividendRatioBeforeTax = dividendRatioBeforeTax;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_Dividend.ActualRatioAfterTax
     *
     * @return the value of MF_Dividend.ActualRatioAfterTax
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public BigDecimal getActualRatioAfterTax() {
        return actualRatioAfterTax;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_Dividend.ActualRatioAfterTax
     *
     * @param actualRatioAfterTax
     *            the value for MF_Dividend.ActualRatioAfterTax
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public void setActualRatioAfterTax(BigDecimal actualRatioAfterTax) {
        this.actualRatioAfterTax = actualRatioAfterTax;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_Dividend.Dividendsum
     *
     * @return the value of MF_Dividend.Dividendsum
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public BigDecimal getDividendsum() {
        return dividendsum;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_Dividend.Dividendsum
     *
     * @param dividendsum
     *            the value for MF_Dividend.Dividendsum
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public void setDividendsum(BigDecimal dividendsum) {
        this.dividendsum = dividendsum;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_Dividend.ReDate
     *
     * @return the value of MF_Dividend.ReDate
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public Date getReDate() {
        return reDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_Dividend.ReDate
     *
     * @param reDate
     *            the value for MF_Dividend.ReDate
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public void setReDate(Date reDate) {
        this.reDate = reDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_Dividend.ExRightDate
     *
     * @return the value of MF_Dividend.ExRightDate
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public Date getExRightDate() {
        return exRightDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_Dividend.ExRightDate
     *
     * @param exRightDate
     *            the value for MF_Dividend.ExRightDate
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public void setExRightDate(Date exRightDate) {
        this.exRightDate = exRightDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_Dividend.ExecuteDate
     *
     * @return the value of MF_Dividend.ExecuteDate
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public Date getExecuteDate() {
        return executeDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_Dividend.ExecuteDate
     *
     * @param executeDate
     *            the value for MF_Dividend.ExecuteDate
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public void setExecuteDate(Date executeDate) {
        this.executeDate = executeDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_Dividend.SchemeModification
     *
     * @return the value of MF_Dividend.SchemeModification
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public String getSchemeModification() {
        return schemeModification;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_Dividend.SchemeModification
     *
     * @param schemeModification
     *            the value for MF_Dividend.SchemeModification
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public void setSchemeModification(String schemeModification) {
        this.schemeModification = schemeModification == null ? null : schemeModification.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_Dividend.XGRQ
     *
     * @return the value of MF_Dividend.XGRQ
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public Date getXGRQ() {
        return XGRQ;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_Dividend.XGRQ
     *
     * @param XGRQ
     *            the value for MF_Dividend.XGRQ
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public void setXGRQ(Date XGRQ) {
        this.XGRQ = XGRQ;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_Dividend.JSID
     *
     * @return the value of MF_Dividend.JSID
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public Long getJSID() {
        return JSID;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_Dividend.JSID
     *
     * @param JSID
     *            the value for MF_Dividend.JSID
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public void setJSID(Long JSID) {
        this.JSID = JSID;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_Dividend.ReinvestDay
     *
     * @return the value of MF_Dividend.ReinvestDay
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public Date getReinvestDay() {
        return reinvestDay;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_Dividend.ReinvestDay
     *
     * @param reinvestDay
     *            the value for MF_Dividend.ReinvestDay
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public void setReinvestDay(Date reinvestDay) {
        this.reinvestDay = reinvestDay;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_Dividend.AccountDay
     *
     * @return the value of MF_Dividend.AccountDay
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public Date getAccountDay() {
        return accountDay;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_Dividend.AccountDay
     *
     * @param accountDay
     *            the value for MF_Dividend.AccountDay
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public void setAccountDay(Date accountDay) {
        this.accountDay = accountDay;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_Dividend.RedemptionDay
     *
     * @return the value of MF_Dividend.RedemptionDay
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public Date getRedemptionDay() {
        return redemptionDay;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_Dividend.RedemptionDay
     *
     * @param redemptionDay
     *            the value for MF_Dividend.RedemptionDay
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public void setRedemptionDay(Date redemptionDay) {
        this.redemptionDay = redemptionDay;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_Dividend.UnitProfitYTD
     *
     * @return the value of MF_Dividend.UnitProfitYTD
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public BigDecimal getUnitProfitYTD() {
        return unitProfitYTD;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_Dividend.UnitProfitYTD
     *
     * @param unitProfitYTD
     *            the value for MF_Dividend.UnitProfitYTD
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public void setUnitProfitYTD(BigDecimal unitProfitYTD) {
        this.unitProfitYTD = unitProfitYTD;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_Dividend.DividendSumYTD
     *
     * @return the value of MF_Dividend.DividendSumYTD
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public BigDecimal getDividendSumYTD() {
        return dividendSumYTD;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_Dividend.DividendSumYTD
     *
     * @param dividendSumYTD
     *            the value for MF_Dividend.DividendSumYTD
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public void setDividendSumYTD(BigDecimal dividendSumYTD) {
        this.dividendSumYTD = dividendSumYTD;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_Dividend.DividendTimesYTD
     *
     * @return the value of MF_Dividend.DividendTimesYTD
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public Integer getDividendTimesYTD() {
        return dividendTimesYTD;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_Dividend.DividendTimesYTD
     *
     * @param dividendTimesYTD
     *            the value for MF_Dividend.DividendTimesYTD
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public void setDividendTimesYTD(Integer dividendTimesYTD) {
        this.dividendTimesYTD = dividendTimesYTD;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_Dividend.DiviSumSinceInception
     *
     * @return the value of MF_Dividend.DiviSumSinceInception
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public BigDecimal getDiviSumSinceInception() {
        return diviSumSinceInception;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_Dividend.DiviSumSinceInception
     *
     * @param diviSumSinceInception
     *            the value for MF_Dividend.DiviSumSinceInception
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public void setDiviSumSinceInception(BigDecimal diviSumSinceInception) {
        this.diviSumSinceInception = diviSumSinceInception;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_Dividend.DiviTimesSinceIncepion
     *
     * @return the value of MF_Dividend.DiviTimesSinceIncepion
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public Integer getDiviTimesSinceIncepion() {
        return diviTimesSinceIncepion;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_Dividend.DiviTimesSinceIncepion
     *
     * @param diviTimesSinceIncepion
     *            the value for MF_Dividend.DiviTimesSinceIncepion
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public void setDiviTimesSinceIncepion(Integer diviTimesSinceIncepion) {
        this.diviTimesSinceIncepion = diviTimesSinceIncepion;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_Dividend.EventProcedureCode
     *
     * @return the value of MF_Dividend.EventProcedureCode
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public Integer getEventProcedureCode() {
        return eventProcedureCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_Dividend.EventProcedureCode
     *
     * @param eventProcedureCode
     *            the value for MF_Dividend.EventProcedureCode
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public void setEventProcedureCode(Integer eventProcedureCode) {
        this.eventProcedureCode = eventProcedureCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_Dividend.EventProcedure
     *
     * @return the value of MF_Dividend.EventProcedure
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public String getEventProcedure() {
        return eventProcedure;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_Dividend.EventProcedure
     *
     * @param eventProcedure
     *            the value for MF_Dividend.EventProcedure
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public void setEventProcedure(String eventProcedure) {
        this.eventProcedure = eventProcedure == null ? null : eventProcedure.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_Dividend.ExRightDateEX
     *
     * @return the value of MF_Dividend.ExRightDateEX
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public Date getExRightDateEX() {
        return exRightDateEX;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_Dividend.ExRightDateEX
     *
     * @param exRightDateEX
     *            the value for MF_Dividend.ExRightDateEX
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public void setExRightDateEX(Date exRightDateEX) {
        this.exRightDateEX = exRightDateEX;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_Dividend.ExRightDateCurbEX
     *
     * @return the value of MF_Dividend.ExRightDateCurbEX
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public Date getExRightDateCurbEX() {
        return exRightDateCurbEX;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_Dividend.ExRightDateCurbEX
     *
     * @param exRightDateCurbEX
     *            the value for MF_Dividend.ExRightDateCurbEX
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public void setExRightDateCurbEX(Date exRightDateCurbEX) {
        this.exRightDateCurbEX = exRightDateCurbEX;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_Dividend.ExecuteDateEX
     *
     * @return the value of MF_Dividend.ExecuteDateEX
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public Date getExecuteDateEX() {
        return executeDateEX;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_Dividend.ExecuteDateEX
     *
     * @param executeDateEX
     *            the value for MF_Dividend.ExecuteDateEX
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public void setExecuteDateEX(Date executeDateEX) {
        this.executeDateEX = executeDateEX;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_Dividend.ExecuteDateCurbEX
     *
     * @return the value of MF_Dividend.ExecuteDateCurbEX
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public Date getExecuteDateCurbEX() {
        return executeDateCurbEX;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_Dividend.ExecuteDateCurbEX
     *
     * @param executeDateCurbEX
     *            the value for MF_Dividend.ExecuteDateCurbEX
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public void setExecuteDateCurbEX(Date executeDateCurbEX) {
        this.executeDateCurbEX = executeDateCurbEX;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_Dividend.DistributableProfits
     *
     * @return the value of MF_Dividend.DistributableProfits
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public BigDecimal getDistributableProfits() {
        return distributableProfits;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_Dividend.DistributableProfits
     *
     * @param distributableProfits
     *            the value for MF_Dividend.DistributableProfits
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public void setDistributableProfits(BigDecimal distributableProfits) {
        this.distributableProfits = distributableProfits;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column MF_Dividend.AllocationValue
     *
     * @return the value of MF_Dividend.AllocationValue
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public BigDecimal getAllocationValue() {
        return allocationValue;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column MF_Dividend.AllocationValue
     *
     * @param allocationValue
     *            the value for MF_Dividend.AllocationValue
     *
     * @mbggenerated Tue Oct 11 10:24:48 CST 2016
     */
    public void setAllocationValue(BigDecimal allocationValue) {
        this.allocationValue = allocationValue;
    }
}