package com.codi.fundData.domain;

import java.util.Date;

import com.codi.base.domain.BaseDomain;

/**
 * 证券产品(股票、基金、债券)
 * 
 * @author shi.pengyan
 * @date 2016年9月22日 下午1:52:27
 */
public class SecurityProduct extends BaseDomain {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column SecuMain.ID
     *
     * @mbggenerated Thu Sep 22 13:52:05 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column SecuMain.InnerCode
     *
     * @mbggenerated Thu Sep 22 13:52:05 CST 2016
     */
    private Integer innerCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column SecuMain.CompanyCode
     *
     * @mbggenerated Thu Sep 22 13:52:05 CST 2016
     */
    private Integer companyCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column SecuMain.SecuCode
     *
     * @mbggenerated Thu Sep 22 13:52:05 CST 2016
     */
    private String secuCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column SecuMain.ChiName
     *
     * @mbggenerated Thu Sep 22 13:52:05 CST 2016
     */
    private String chiName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column SecuMain.ChiNameAbbr
     *
     * @mbggenerated Thu Sep 22 13:52:05 CST 2016
     */
    private String chiNameAbbr;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column SecuMain.EngName
     *
     * @mbggenerated Thu Sep 22 13:52:05 CST 2016
     */
    private String engName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column SecuMain.EngNameAbbr
     *
     * @mbggenerated Thu Sep 22 13:52:05 CST 2016
     */
    private String engNameAbbr;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column SecuMain.SecuAbbr
     *
     * @mbggenerated Thu Sep 22 13:52:05 CST 2016
     */
    private String secuAbbr;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column SecuMain.ChiSpelling
     *
     * @mbggenerated Thu Sep 22 13:52:05 CST 2016
     */
    private String chiSpelling;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column SecuMain.SecuMarket
     *
     * @mbggenerated Thu Sep 22 13:52:05 CST 2016
     */
    private Integer secuMarket;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column SecuMain.SecuCategory
     *
     * @mbggenerated Thu Sep 22 13:52:05 CST 2016
     */
    private Integer secuCategory;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column SecuMain.ListedDate
     *
     * @mbggenerated Thu Sep 22 13:52:05 CST 2016
     */
    private Date listedDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column SecuMain.ListedSector
     *
     * @mbggenerated Thu Sep 22 13:52:05 CST 2016
     */
    private Integer listedSector;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column SecuMain.ListedState
     *
     * @mbggenerated Thu Sep 22 13:52:05 CST 2016
     */
    private Integer listedState;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column SecuMain.XGRQ
     *
     * @mbggenerated Thu Sep 22 13:52:05 CST 2016
     */
    private Date xgrq;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column SecuMain.JSID
     *
     * @mbggenerated Thu Sep 22 13:52:05 CST 2016
     */
    private Long jsid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column SecuMain.ISIN
     *
     * @mbggenerated Thu Sep 22 13:52:05 CST 2016
     */
    private String isin;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getInnerCode() {
        return innerCode;
    }

    public void setInnerCode(Integer innerCode) {
        this.innerCode = innerCode;
    }

    public Integer getCompanyCode() {
        return companyCode;
    }

    public void setCompanyCode(Integer companyCode) {
        this.companyCode = companyCode;
    }

    public String getSecuCode() {
        return secuCode;
    }

    public void setSecuCode(String secuCode) {
        this.secuCode = secuCode;
    }

    public String getChiName() {
        return chiName;
    }

    public void setChiName(String chiName) {
        this.chiName = chiName;
    }

    public String getChiNameAbbr() {
        return chiNameAbbr;
    }

    public void setChiNameAbbr(String chiNameAbbr) {
        this.chiNameAbbr = chiNameAbbr;
    }

    public String getEngName() {
        return engName;
    }

    public void setEngName(String engName) {
        this.engName = engName;
    }

    public String getEngNameAbbr() {
        return engNameAbbr;
    }

    public void setEngNameAbbr(String engNameAbbr) {
        this.engNameAbbr = engNameAbbr;
    }

    public String getSecuAbbr() {
        return secuAbbr;
    }

    public void setSecuAbbr(String secuAbbr) {
        this.secuAbbr = secuAbbr;
    }

    public String getChiSpelling() {
        return chiSpelling;
    }

    public void setChiSpelling(String chiSpelling) {
        this.chiSpelling = chiSpelling;
    }

    public Integer getSecuMarket() {
        return secuMarket;
    }

    public void setSecuMarket(Integer secuMarket) {
        this.secuMarket = secuMarket;
    }

    public Integer getSecuCategory() {
        return secuCategory;
    }

    public void setSecuCategory(Integer secuCategory) {
        this.secuCategory = secuCategory;
    }

    public Date getListedDate() {
        return listedDate;
    }

    public void setListedDate(Date listedDate) {
        this.listedDate = listedDate;
    }

    public Integer getListedSector() {
        return listedSector;
    }

    public void setListedSector(Integer listedSector) {
        this.listedSector = listedSector;
    }

    public Integer getListedState() {
        return listedState;
    }

    public void setListedState(Integer listedState) {
        this.listedState = listedState;
    }

    public Date getXgrq() {
        return xgrq;
    }

    public void setXgrq(Date xgrq) {
        this.xgrq = xgrq;
    }

    public Long getJsid() {
        return jsid;
    }

    public void setJsid(Long jsid) {
        this.jsid = jsid;
    }

    public String getIsin() {
        return isin;
    }

    public void setIsin(String isin) {
        this.isin = isin;
    }

}