package com.codi.bus.core.dao.impl;

import com.codi.base.dao.BaseDAOImpl;
import com.codi.bus.core.dao.UserProfileDao;
import com.codi.bus.core.domain.UserProfile;
import org.springframework.stereotype.Repository;

import java.util.Date;

/**
 * Created by Shangdu Lin on 2017/6/19 16:54.
 */
@Repository("userProfileDao")
public class UserProfileDaoImpl extends BaseDAOImpl<UserProfile> implements UserProfileDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uf_user_profile
     *
     * @param record
     * @mbggenerated Mon Jun 19 16:43:10 CST 2017
     */
    @Override
    public Long insertSelective(UserProfile record) {
        record.setCreateDate(new Date());
        this.insert(this.generateStatement("insertSelective"), record);
        return record.getProfileId();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uf_user_profile
     *
     * @param userId
     * @mbggenerated Mon Jun 19 16:43:10 CST 2017
     */
    @Override
    public UserProfile selectByUserId(Long userId) {
        return this.getObject(this.generateStatement("selectByUserId"),userId);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uf_user_profile
     *
     * @param record
     * @mbggenerated Mon Jun 19 16:43:10 CST 2017
     */
    @Override
    public int updateByUserIdSelective(UserProfile record) {
        record.setLastUpdatedDate(new Date());
        return this.update(this.generateStatement("updateByUserIdSelective"),record);
    }
}
