package com.codi.bus.core.domain;

import java.util.Date;

public class CardBin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_cb_card_bin.rule_cb_id
     *
     * @mbggenerated Wed Aug 31 13:22:13 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_cb_card_bin.rule_cb_bin
     *
     * @mbggenerated Wed Aug 31 13:22:13 CST 2016
     */
    private String bin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_cb_card_bin.rule_cb_bank_code
     *
     * @mbggenerated Wed Aug 31 13:22:13 CST 2016
     */
    private String bankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_cb_card_bin.rule_cb_bank_name
     *
     * @mbggenerated Wed Aug 31 13:22:13 CST 2016
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_cb_card_bin.rule_cb_card_name
     *
     * @mbggenerated Wed Aug 31 13:22:13 CST 2016
     */
    private String cardName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_cb_card_bin.rule_cb_card_type
     *
     * @mbggenerated Wed Aug 31 13:22:13 CST 2016
     */
    private String cardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_cb_card_bin.rule_cb_create_date
     *
     * @mbggenerated Wed Aug 31 13:22:13 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_cb_card_bin.rule_cb_create_user_id
     *
     * @mbggenerated Wed Aug 31 13:22:13 CST 2016
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_cb_card_bin.rule_cb_last_updated_date
     *
     * @mbggenerated Wed Aug 31 13:22:13 CST 2016
     */
    private Date lastUpdatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_cb_card_bin.rule_cb_last_updated_user_id
     *
     * @mbggenerated Wed Aug 31 13:22:13 CST 2016
     */
    private String lastUpdatedUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_cb_card_bin.rule_cb_id
     *
     * @return the value of rule_cb_card_bin.rule_cb_id
     *
     * @mbggenerated Wed Aug 31 13:22:13 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_cb_card_bin.rule_cb_id
     *
     * @param Id the value for rule_cb_card_bin.rule_cb_id
     *
     * @mbggenerated Wed Aug 31 13:22:13 CST 2016
     */
    public void setId(Long Id) {
        this.id = Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_cb_card_bin.rule_cb_bin
     *
     * @return the value of rule_cb_card_bin.rule_cb_bin
     *
     * @mbggenerated Wed Aug 31 13:22:13 CST 2016
     */
    public String getBin() {
        return bin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_cb_card_bin.rule_cb_bin
     *
     * @param bin the value for rule_cb_card_bin.rule_cb_bin
     *
     * @mbggenerated Wed Aug 31 13:22:13 CST 2016
     */
    public void setBin(String bin) {
        this.bin = bin == null ? null : bin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_cb_card_bin.rule_cb_bank_code
     *
     * @return the value of rule_cb_card_bin.rule_cb_bank_code
     *
     * @mbggenerated Wed Aug 31 13:22:13 CST 2016
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_cb_card_bin.rule_cb_bank_code
     *
     * @param bankCode the value for rule_cb_card_bin.rule_cb_bank_code
     *
     * @mbggenerated Wed Aug 31 13:22:13 CST 2016
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode == null ? null : bankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_cb_card_bin.rule_cb_bank_name
     *
     * @return the value of rule_cb_card_bin.rule_cb_bank_name
     *
     * @mbggenerated Wed Aug 31 13:22:13 CST 2016
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_cb_card_bin.rule_cb_bank_name
     *
     * @param bankName the value for rule_cb_card_bin.rule_cb_bank_name
     *
     * @mbggenerated Wed Aug 31 13:22:13 CST 2016
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_cb_card_bin.rule_cb_card_name
     *
     * @return the value of rule_cb_card_bin.rule_cb_card_name
     *
     * @mbggenerated Wed Aug 31 13:22:13 CST 2016
     */
    public String getCardName() {
        return cardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_cb_card_bin.rule_cb_card_name
     *
     * @param cardName the value for rule_cb_card_bin.rule_cb_card_name
     *
     * @mbggenerated Wed Aug 31 13:22:13 CST 2016
     */
    public void setCardName(String cardName) {
        this.cardName = cardName == null ? null : cardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_cb_card_bin.rule_cb_card_type
     *
     * @return the value of rule_cb_card_bin.rule_cb_card_type
     *
     * @mbggenerated Wed Aug 31 13:22:13 CST 2016
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_cb_card_bin.rule_cb_card_type
     *
     * @param cardType the value for rule_cb_card_bin.rule_cb_card_type
     *
     * @mbggenerated Wed Aug 31 13:22:13 CST 2016
     */
    public void setCardType(String cardType) {
        this.cardType = cardType == null ? null : cardType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_cb_card_bin.rule_cb_create_date
     *
     * @return the value of rule_cb_card_bin.rule_cb_create_date
     *
     * @mbggenerated Wed Aug 31 13:22:13 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_cb_card_bin.rule_cb_create_date
     *
     * @param createDate the value for rule_cb_card_bin.rule_cb_create_date
     *
     * @mbggenerated Wed Aug 31 13:22:13 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_cb_card_bin.rule_cb_create_user_id
     *
     * @return the value of rule_cb_card_bin.rule_cb_create_user_id
     *
     * @mbggenerated Wed Aug 31 13:22:13 CST 2016
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_cb_card_bin.rule_cb_create_user_id
     *
     * @param createUserId the value for rule_cb_card_bin.rule_cb_create_user_id
     *
     * @mbggenerated Wed Aug 31 13:22:13 CST 2016
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_cb_card_bin.rule_cb_last_updated_date
     *
     * @return the value of rule_cb_card_bin.rule_cb_last_updated_date
     *
     * @mbggenerated Wed Aug 31 13:22:13 CST 2016
     */
    public Date getLastUpdatedDate() {
        return lastUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_cb_card_bin.rule_cb_last_updated_date
     *
     * @param lastUpdatedDate the value for rule_cb_card_bin.rule_cb_last_updated_date
     *
     * @mbggenerated Wed Aug 31 13:22:13 CST 2016
     */
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_cb_card_bin.rule_cb_last_updated_user_id
     *
     * @return the value of rule_cb_card_bin.rule_cb_last_updated_user_id
     *
     * @mbggenerated Wed Aug 31 13:22:13 CST 2016
     */
    public String getLastUpdatedUserId() {
        return lastUpdatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_cb_card_bin.rule_cb_last_updated_user_id
     *
     * @param lastUpdatedUserId the value for rule_cb_card_bin.rule_cb_last_updated_user_id
     *
     * @mbggenerated Wed Aug 31 13:22:13 CST 2016
     */
    public void setLastUpdatedUserId(String lastUpdatedUserId) {
        this.lastUpdatedUserId = lastUpdatedUserId == null ? null : lastUpdatedUserId.trim();
    }
}