package com.codi.bus.core.domain;

public class LookupKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_lu_lookup.rule_lu_type
     *
     * @mbggenerated Sun Oct 09 15:39:40 CST 2016
     */
    private String ruleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_lu_lookup.rule_lu_value
     *
     * @mbggenerated Sun Oct 09 15:39:40 CST 2016
     */
    private String ruleValue;

	public String getRuleType() {
		return ruleType;
	}

	public void setRuleType(String ruleType) {
		this.ruleType = ruleType;
	}

	public String getRuleValue() {
		return ruleValue;
	}

	public void setRuleValue(String ruleValue) {
		this.ruleValue = ruleValue;
	}

}