package com.codi.bus.core.domain;

import com.alibaba.fastjson.annotation.JSONField;

import java.util.Date;

public class OperationContent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_operation_content.oc_id
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_operation_content.oc_title
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_operation_content.oc_sub_title
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    private String subTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_operation_content.oc_description
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_operation_content.oc_tag
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_operation_content.oc_style
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    private String style;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_operation_content.oc_block_name
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    private String blockName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_operation_content.oc_priority
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_operation_content.oc_indicant
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    private String indicant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_operation_content.oc_indicant_description
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    private String indicantDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_operation_content.oc_url
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_operation_content.oc_status
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_operation_content.oc_extra_map
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    private String extraMap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_operation_content.oc_create_time
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oc_operation_content.oc_last_updated_time
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date lastUpdatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_operation_content.oc_id
     *
     * @return the value of oc_operation_content.oc_id
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_operation_content.oc_id
     *
     * @param id the value for oc_operation_content.oc_id
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_operation_content.oc_title
     *
     * @return the value of oc_operation_content.oc_title
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_operation_content.oc_title
     *
     * @param title the value for oc_operation_content.oc_title
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_operation_content.oc_sub_title
     *
     * @return the value of oc_operation_content.oc_sub_title
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    public String getSubTitle() {
        return subTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_operation_content.oc_sub_title
     *
     * @param subTitle the value for oc_operation_content.oc_sub_title
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    public void setSubTitle(String subTitle) {
        this.subTitle = subTitle == null ? null : subTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_operation_content.oc_description
     *
     * @return the value of oc_operation_content.oc_description
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_operation_content.oc_description
     *
     * @param description the value for oc_operation_content.oc_description
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_operation_content.oc_tag
     *
     * @return the value of oc_operation_content.oc_tag
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_operation_content.oc_tag
     *
     * @param tag the value for oc_operation_content.oc_tag
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_operation_content.oc_style
     *
     * @return the value of oc_operation_content.oc_style
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    public String getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_operation_content.oc_style
     *
     * @param style the value for oc_operation_content.oc_style
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    public void setStyle(String style) {
        this.style = style == null ? null : style.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_operation_content.oc_block_name
     *
     * @return the value of oc_operation_content.oc_block_name
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    public String getBlockName() {
        return blockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_operation_content.oc_block_name
     *
     * @param blockName the value for oc_operation_content.oc_block_name
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    public void setBlockName(String blockName) {
        this.blockName = blockName == null ? null : blockName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_operation_content.oc_priority
     *
     * @return the value of oc_operation_content.oc_priority
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_operation_content.oc_priority
     *
     * @param priority the value for oc_operation_content.oc_priority
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_operation_content.oc_indicant
     *
     * @return the value of oc_operation_content.oc_indicant
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    public String getIndicant() {
        return indicant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_operation_content.oc_indicant
     *
     * @param indicant the value for oc_operation_content.oc_indicant
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    public void setIndicant(String indicant) {
        this.indicant = indicant == null ? null : indicant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_operation_content.oc_indicant_description
     *
     * @return the value of oc_operation_content.oc_indicant_description
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    public String getIndicantDescription() {
        return indicantDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_operation_content.oc_indicant_description
     *
     * @param indicantDescription the value for oc_operation_content.oc_indicant_description
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    public void setIndicantDescription(String indicantDescription) {
        this.indicantDescription = indicantDescription == null ? null : indicantDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_operation_content.oc_url
     *
     * @return the value of oc_operation_content.oc_url
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_operation_content.oc_url
     *
     * @param url the value for oc_operation_content.oc_url
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_operation_content.oc_status
     *
     * @return the value of oc_operation_content.oc_status
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_operation_content.oc_status
     *
     * @param status the value for oc_operation_content.oc_status
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_operation_content.oc_extra_map
     *
     * @return the value of oc_operation_content.oc_extra_map
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    public String getExtraMap() {
        return extraMap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_operation_content.oc_extra_map
     *
     * @param extraMap the value for oc_operation_content.oc_extra_map
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    public void setExtraMap(String extraMap) {
        this.extraMap = extraMap == null ? null : extraMap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_operation_content.oc_create_time
     *
     * @return the value of oc_operation_content.oc_create_time
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_operation_content.oc_create_time
     *
     * @param createTime the value for oc_operation_content.oc_create_time
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oc_operation_content.oc_last_updated_time
     *
     * @return the value of oc_operation_content.oc_last_updated_time
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    public Date getLastUpdatedTime() {
        return lastUpdatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oc_operation_content.oc_last_updated_time
     *
     * @param lastUpdatedTime the value for oc_operation_content.oc_last_updated_time
     *
     * @mbggenerated Fri Nov 18 17:55:45 CST 2016
     */
    public void setLastUpdatedTime(Date lastUpdatedTime) {
        this.lastUpdatedTime = lastUpdatedTime;
    }

    private String indicantType;

    public String getIndicantType() {
        return indicantType;
    }

    public void setIndicantType(String indicantType) {
        this.indicantType = indicantType;
    }

    private String version;

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }
}
