package com.codi.bus.core.domain;

import java.math.BigDecimal;
import java.util.Date;

public class OrderFund {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column of_order_fund.of_order_fund_id
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    private Long orderFundId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column of_order_fund.to_order_id
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column of_order_fund.of_fund_status
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    private Integer fundStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column of_order_fund.of_fund_name
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    private String fundName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column of_order_fund.of_fund_code
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    private String fundCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column of_order_fund.of_share_type
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    private String shareType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column of_order_fund.of_net_value
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    private BigDecimal netValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column of_order_fund.of_shares
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    private BigDecimal shares;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column of_order_fund.of_fund_balance
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    private BigDecimal fundBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column of_order_fund.of_oppo_fund_account
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    private String oppoFundAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column of_order_fund.of_create_date
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column of_order_fund.of_create_user_id
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column of_order_fund.of_last_updated_date
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    private Date lastUpdatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column of_order_fund.of_last_updated_user_id
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    private String lastUpdatedUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column of_order_fund.of_is_valid
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    private Boolean isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column of_order_fund.external_apply_no
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    private String externalApplyNo;
    
    private String externalUndoNo;
    
    /**
     * 定投申购、变更时的定投协议号
     */
    private String externalScheduledProtocolId;
    
    /**
     * 协议周期单位('年','月','日')
     */
    private String externalProtocolPeriodUnit;
    
    /**
     * 定投交易日
     */
    private Long externalProtocolFixDay;
    
    public String getExternalUndoNo() {
        return externalUndoNo;
    }
    
    public void setExternalUndoNo(String externalUndoNo) {
        this.externalUndoNo = externalUndoNo;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column of_order_fund.of_order_fund_id
     *
     * @return the value of of_order_fund.of_order_fund_id
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    public Long getOrderFundId() {
        return orderFundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column of_order_fund.of_order_fund_id
     *
     * @param ofOrderFundId the value for of_order_fund.of_order_fund_id
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    public void setOrderFundId(Long orderFundId) {
        this.orderFundId = orderFundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column of_order_fund.to_order_id
     *
     * @return the value of of_order_fund.to_order_id
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column of_order_fund.to_order_id
     *
     * @param toOrderId the value for of_order_fund.to_order_id
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column of_order_fund.of_fund_status
     *
     * @return the value of of_order_fund.of_fund_status
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    public Integer getFundStatus() {
        return fundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column of_order_fund.of_fund_status
     *
     * @param fundStatus the value for of_order_fund.of_fund_status
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    public void setFundStatus(Integer fundStatus) {
        this.fundStatus = fundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column of_order_fund.of_fund_name
     *
     * @return the value of of_order_fund.of_fund_name
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    public String getFundName() {
        return fundName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column of_order_fund.of_fund_name
     *
     * @param fundName the value for of_order_fund.of_fund_name
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    public void setFundName(String fundName) {
        this.fundName = fundName == null ? null : fundName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column of_order_fund.of_fund_code
     *
     * @return the value of of_order_fund.of_fund_code
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    public String getFundCode() {
        return fundCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column of_order_fund.of_fund_code
     *
     * @param fundCode the value for of_order_fund.of_fund_code
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    public void setFundCode(String fundCode) {
        this.fundCode = fundCode == null ? null : fundCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column of_order_fund.of_share_type
     *
     * @return the value of of_order_fund.of_share_type
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    public String getShareType() {
        return shareType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column of_order_fund.of_share_type
     *
     * @param shareType the value for of_order_fund.of_share_type
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    public void setShareType(String shareType) {
        this.shareType = shareType == null ? null : shareType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column of_order_fund.of_net_value
     *
     * @return the value of of_order_fund.of_net_value
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    public BigDecimal getNetValue() {
        return netValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column of_order_fund.of_net_value
     *
     * @param netValue the value for of_order_fund.of_net_value
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    public void setNetValue(BigDecimal netValue) {
        this.netValue = netValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column of_order_fund.of_shares
     *
     * @return the value of of_order_fund.of_shares
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    public BigDecimal getShares() {
        return shares;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column of_order_fund.of_shares
     *
     * @param shares the value for of_order_fund.of_shares
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    public void setShares(BigDecimal shares) {
        this.shares = shares;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column of_order_fund.of_fund_balance
     *
     * @return the value of of_order_fund.of_fund_balance
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    public BigDecimal getFundBalance() {
        return fundBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column of_order_fund.of_fund_balance
     *
     * @param fundBalance the value for of_order_fund.of_fund_balance
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    public void setFundBalance(BigDecimal fundBalance) {
        this.fundBalance = fundBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column of_order_fund.of_oppo_fund_account
     *
     * @return the value of of_order_fund.of_oppo_fund_account
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    public String getOppoFundAccount() {
        return oppoFundAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column of_order_fund.of_oppo_fund_account
     *
     * @param oppoFundAccount the value for of_order_fund.of_oppo_fund_account
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    public void setOfOppoFundAccount(String oppoFundAccount) {
        this.oppoFundAccount = oppoFundAccount == null ? null : oppoFundAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column of_order_fund.of_create_date
     *
     * @return the value of of_order_fund.of_create_date
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column of_order_fund.of_create_date
     *
     * @param createDate the value for of_order_fund.of_create_date
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column of_order_fund.of_create_user_id
     *
     * @return the value of of_order_fund.of_create_user_id
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column of_order_fund.of_create_user_id
     *
     * @param createUserId the value for of_order_fund.of_create_user_id
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column of_order_fund.of_last_updated_date
     *
     * @return the value of of_order_fund.of_last_updated_date
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    public Date getLastUpdatedDate() {
        return lastUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column of_order_fund.of_last_updated_date
     *
     * @param lastUpdatedDate the value for of_order_fund.of_last_updated_date
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column of_order_fund.of_last_updated_user_id
     *
     * @return the value of of_order_fund.of_last_updated_user_id
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    public String getLastUpdatedUserId() {
        return lastUpdatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column of_order_fund.of_last_updated_user_id
     *
     * @param lastUpdatedUserId the value for of_order_fund.of_last_updated_user_id
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    public void setLastUpdatedUserId(String lastUpdatedUserId) {
        this.lastUpdatedUserId = lastUpdatedUserId == null ? null : lastUpdatedUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column of_order_fund.of_is_valid
     *
     * @return the value of of_order_fund.of_is_valid
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    public Boolean getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column of_order_fund.of_is_valid
     *
     * @param isValid the value for of_order_fund.of_is_valid
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    public void setIsValid(Boolean isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column of_order_fund.external_apply_no
     *
     * @return the value of of_order_fund.external_apply_no
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    public String getExternalApplyNo() {
        return externalApplyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column of_order_fund.external_apply_no
     *
     * @param externalApplyNo the value for of_order_fund.external_apply_no
     *
     * @mbggenerated Mon Sep 12 15:38:37 CST 2016
     */
    public void setExternalApplyNo(String externalApplyNo) {
        this.externalApplyNo = externalApplyNo == null ? null : externalApplyNo.trim();
    }

    public String getExternalScheduledProtocolId() {
        return externalScheduledProtocolId;
    }

    public void setExternalScheduledProtocolId(String externalScheduledProtocolId) {
        this.externalScheduledProtocolId = externalScheduledProtocolId;
    }

    public String getExternalProtocolPeriodUnit() {
        return externalProtocolPeriodUnit;
    }

    public void setExternalProtocolPeriodUnit(String externalProtocolPeriodUnit) {
        this.externalProtocolPeriodUnit = externalProtocolPeriodUnit;
    }

    public Long getExternalProtocolFixDay() {
        return externalProtocolFixDay;
    }

    public void setExternalProtocolFixDay(Long externalProtocolFixDay) {
        this.externalProtocolFixDay = externalProtocolFixDay;
    }
    
}