package com.codi.bus.core.domain;

import java.math.BigDecimal;
import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;
import com.codi.base.domain.BaseDomain;

/**
 * 深沪300数据
 * 
 * @author shi.pengyan
 * @date 2016年11月3日 上午9:39:13
 */
public class StaticSH300 extends BaseDomain {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column STATIC_SH300.ID
     *
     * @mbggenerated Thu Nov 03 10:57:49 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column STATIC_SH300.TRADING_DATE
     *
     * @mbggenerated Thu Nov 03 10:57:49 CST 2016
     */
    @JSONField(format = "yyyy-MM-dd")
    private Date tradingDate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column STATIC_SH300.OPEN_PRICE
     *
     * @mbggenerated Thu Nov 03 10:57:49 CST 2016
     */
    private BigDecimal openPrice;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column STATIC_SH300.CLOSE_PRICE
     *
     * @mbggenerated Thu Nov 03 10:57:49 CST 2016
     */
    private BigDecimal closePrice;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column STATIC_SH300.MAX_PRICE
     *
     * @mbggenerated Thu Nov 03 10:57:49 CST 2016
     */
    private BigDecimal maxPrice;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column STATIC_SH300.MIN_PRICE
     *
     * @mbggenerated Thu Nov 03 10:57:49 CST 2016
     */
    private BigDecimal minPrice;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column STATIC_SH300.TURNOVER_VOLUME
     *
     * @mbggenerated Thu Nov 03 10:57:49 CST 2016
     */
    private BigDecimal turnoverVolume;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column STATIC_SH300.DAILY_GROWTH_RATE
     *
     * @mbggenerated Thu Nov 03 10:57:49 CST 2016
     */
    private BigDecimal dailyGrowthRate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column STATIC_SH300.CREATE_DATE
     *
     * @mbggenerated Thu Nov 03 10:57:49 CST 2016
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column STATIC_SH300.ID
     *
     * @return the value of STATIC_SH300.ID
     *
     * @mbggenerated Thu Nov 03 10:57:49 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column STATIC_SH300.ID
     *
     * @param id
     *            the value for STATIC_SH300.ID
     *
     * @mbggenerated Thu Nov 03 10:57:49 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column STATIC_SH300.TRADING_DATE
     *
     * @return the value of STATIC_SH300.TRADING_DATE
     *
     * @mbggenerated Thu Nov 03 10:57:49 CST 2016
     */
    public Date getTradingDate() {
        return tradingDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column STATIC_SH300.TRADING_DATE
     *
     * @param tradingDate
     *            the value for STATIC_SH300.TRADING_DATE
     *
     * @mbggenerated Thu Nov 03 10:57:49 CST 2016
     */
    public void setTradingDate(Date tradingDate) {
        this.tradingDate = tradingDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column STATIC_SH300.OPEN_PRICE
     *
     * @return the value of STATIC_SH300.OPEN_PRICE
     *
     * @mbggenerated Thu Nov 03 10:57:49 CST 2016
     */
    public BigDecimal getOpenPrice() {
        return openPrice;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column STATIC_SH300.OPEN_PRICE
     *
     * @param openPrice
     *            the value for STATIC_SH300.OPEN_PRICE
     *
     * @mbggenerated Thu Nov 03 10:57:49 CST 2016
     */
    public void setOpenPrice(BigDecimal openPrice) {
        this.openPrice = openPrice;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column STATIC_SH300.CLOSE_PRICE
     *
     * @return the value of STATIC_SH300.CLOSE_PRICE
     *
     * @mbggenerated Thu Nov 03 10:57:49 CST 2016
     */
    public BigDecimal getClosePrice() {
        return closePrice;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column STATIC_SH300.CLOSE_PRICE
     *
     * @param closePrice
     *            the value for STATIC_SH300.CLOSE_PRICE
     *
     * @mbggenerated Thu Nov 03 10:57:49 CST 2016
     */
    public void setClosePrice(BigDecimal closePrice) {
        this.closePrice = closePrice;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column STATIC_SH300.MAX_PRICE
     *
     * @return the value of STATIC_SH300.MAX_PRICE
     *
     * @mbggenerated Thu Nov 03 10:57:49 CST 2016
     */
    public BigDecimal getMaxPrice() {
        return maxPrice;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column STATIC_SH300.MAX_PRICE
     *
     * @param maxPrice
     *            the value for STATIC_SH300.MAX_PRICE
     *
     * @mbggenerated Thu Nov 03 10:57:49 CST 2016
     */
    public void setMaxPrice(BigDecimal maxPrice) {
        this.maxPrice = maxPrice;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column STATIC_SH300.MIN_PRICE
     *
     * @return the value of STATIC_SH300.MIN_PRICE
     *
     * @mbggenerated Thu Nov 03 10:57:49 CST 2016
     */
    public BigDecimal getMinPrice() {
        return minPrice;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column STATIC_SH300.MIN_PRICE
     *
     * @param minPrice
     *            the value for STATIC_SH300.MIN_PRICE
     *
     * @mbggenerated Thu Nov 03 10:57:49 CST 2016
     */
    public void setMinPrice(BigDecimal minPrice) {
        this.minPrice = minPrice;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column STATIC_SH300.TURNOVER_VOLUME
     *
     * @return the value of STATIC_SH300.TURNOVER_VOLUME
     *
     * @mbggenerated Thu Nov 03 10:57:49 CST 2016
     */
    public BigDecimal getTurnoverVolume() {
        return turnoverVolume;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column STATIC_SH300.TURNOVER_VOLUME
     *
     * @param turnoverVolume
     *            the value for STATIC_SH300.TURNOVER_VOLUME
     *
     * @mbggenerated Thu Nov 03 10:57:49 CST 2016
     */
    public void setTurnoverVolume(BigDecimal turnoverVolume) {
        this.turnoverVolume = turnoverVolume;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column STATIC_SH300.DAILY_GROWTH_RATE
     *
     * @return the value of STATIC_SH300.DAILY_GROWTH_RATE
     *
     * @mbggenerated Thu Nov 03 10:57:49 CST 2016
     */
    public BigDecimal getDailyGrowthRate() {
        return dailyGrowthRate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column STATIC_SH300.DAILY_GROWTH_RATE
     *
     * @param dailyGrowthRate
     *            the value for STATIC_SH300.DAILY_GROWTH_RATE
     *
     * @mbggenerated Thu Nov 03 10:57:49 CST 2016
     */
    public void setDailyGrowthRate(BigDecimal dailyGrowthRate) {
        this.dailyGrowthRate = dailyGrowthRate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column STATIC_SH300.CREATE_DATE
     *
     * @return the value of STATIC_SH300.CREATE_DATE
     *
     * @mbggenerated Thu Nov 03 10:57:49 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column STATIC_SH300.CREATE_DATE
     *
     * @param createDate
     *            the value for STATIC_SH300.CREATE_DATE
     *
     * @mbggenerated Thu Nov 03 10:57:49 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}