package com.codi.bus.core.domain;

import java.math.BigDecimal;
import java.util.Date;

public class TradeOrder {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column to_trade_order.to_order_id
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	private Long orderId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column to_trade_order.to_order_sn
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	private String orderSn;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column to_trade_order.ur_user_id
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	private Long userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column to_trade_order.us_channel_id
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	private String channelId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column to_trade_order.to_trade_type
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	private String tradeType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column to_trade_order.to_order_status
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	private Integer orderStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column to_trade_order.to_money_type
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	private Integer moneyType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column to_trade_order.to_order_balance
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	private BigDecimal orderBalance;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column to_trade_order.to_trade_fee
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	private BigDecimal tradeFee;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column to_trade_order.to_apply_date
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	private Date applyDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column to_trade_order.to_confirm_date
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	private Date confirmDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column to_trade_order.to_order_comment
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	private String orderComment;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column to_trade_order.to_bank_code
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	private String bankCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column to_trade_order.to_bank_account
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	private String bankAccount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column to_trade_order.to_payment_type
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	private String paymentType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column to_trade_order.to_create_date
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	private Date createDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column to_trade_order.to_create_user_id
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	private String createUserId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column to_trade_order.to_last_updated_date
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	private Date lastUpdatedDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column to_trade_order.to_last_updated_user_id
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	private String lastUpdatedUserId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column to_trade_order.to_is_valid
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	private Boolean isValid;
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column to_trade_order.to_order_id
	 *
	 * @return the value of to_trade_order.to_order_id
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public Long getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column to_trade_order.to_order_id
	 *
	 * @param orderId
	 *            the value for to_trade_order.to_order_id
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column to_trade_order.to_order_sn
	 *
	 * @return the value of to_trade_order.to_order_sn
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public String getOrderSn() {
		return orderSn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column to_trade_order.to_order_sn
	 *
	 * @param orderSn
	 *            the value for to_trade_order.to_order_sn
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public void setOrderSn(String orderSn) {
		this.orderSn = orderSn == null ? null : orderSn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column to_trade_order.ur_user_id
	 *
	 * @return the value of to_trade_order.ur_user_id
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column to_trade_order.ur_user_id
	 *
	 * @param userId
	 *            the value for to_trade_order.ur_user_id
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column to_trade_order.us_channel_id
	 *
	 * @return the value of to_trade_order.us_channel_id
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public String getChannelId() {
		return channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column to_trade_order.us_channel_id
	 *
	 * @param channelId
	 *            the value for to_trade_order.us_channel_id
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public void setChannelId(String channelId) {
		this.channelId = channelId == null ? null : channelId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column to_trade_order.to_trade_type
	 *
	 * @return the value of to_trade_order.to_trade_type
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public String getTradeType() {
		return tradeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column to_trade_order.to_trade_type
	 *
	 * @param tradeType
	 *            the value for to_trade_order.to_trade_type
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public void setTradeType(String tradeType) {
		this.tradeType = tradeType == null ? null : tradeType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column to_trade_order.to_order_status
	 *
	 * @return the value of to_trade_order.to_order_status
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public Integer getOrderStatus() {
		return orderStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column to_trade_order.to_order_status
	 *
	 * @param orderStatus
	 *            the value for to_trade_order.to_order_status
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public void setOrderStatus(Integer orderStatus) {
		this.orderStatus = orderStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column to_trade_order.to_money_type
	 *
	 * @return the value of to_trade_order.to_money_type
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public Integer getMoneyType() {
		return moneyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column to_trade_order.to_money_type
	 *
	 * @param moneyType
	 *            the value for to_trade_order.to_money_type
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public void setMoneyType(Integer moneyType) {
		this.moneyType = moneyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column to_trade_order.to_order_balance
	 *
	 * @return the value of to_trade_order.to_order_balance
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public BigDecimal getOrderBalance() {
		return orderBalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column to_trade_order.to_order_balance
	 *
	 * @param orderBalance
	 *            the value for to_trade_order.to_order_balance
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public void setOrderBalance(BigDecimal orderBalance) {
		this.orderBalance = orderBalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column to_trade_order.to_trade_fee
	 *
	 * @return the value of to_trade_order.to_trade_fee
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public BigDecimal getTradeFee() {
		return tradeFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column to_trade_order.to_trade_fee
	 *
	 * @param tradeFee
	 *            the value for to_trade_order.to_trade_fee
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public void setTradeFee(BigDecimal tradeFee) {
		this.tradeFee = tradeFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column to_trade_order.to_apply_date
	 *
	 * @return the value of to_trade_order.to_apply_date
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public Date getApplyDate() {
		return applyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column to_trade_order.to_apply_date
	 *
	 * @param applyDate
	 *            the value for to_trade_order.to_apply_date
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public void setApplyDate(Date applyDate) {
		this.applyDate = applyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column to_trade_order.to_confirm_date
	 *
	 * @return the value of to_trade_order.to_confirm_date
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public Date getConfirmDate() {
		return confirmDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column to_trade_order.to_confirm_date
	 *
	 * @param confirmDate
	 *            the value for to_trade_order.to_confirm_date
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public void setConfirmDate(Date confirmDate) {
		this.confirmDate = confirmDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column to_trade_order.to_order_comment
	 *
	 * @return the value of to_trade_order.to_order_comment
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public String getOrderComment() {
		return orderComment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column to_trade_order.to_order_comment
	 *
	 * @param orderComment
	 *            the value for to_trade_order.to_order_comment
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public void setOrderComment(String orderComment) {
		this.orderComment = orderComment == null ? null : orderComment.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column to_trade_order.to_bank_code
	 *
	 * @return the value of to_trade_order.to_bank_code
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public String getBankCode() {
		return bankCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column to_trade_order.to_bank_code
	 *
	 * @param bankCode
	 *            the value for to_trade_order.to_bank_code
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public void setBankCode(String bankCode) {
		this.bankCode = bankCode == null ? null : bankCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column to_trade_order.to_bank_account
	 *
	 * @return the value of to_trade_order.to_bank_account
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public String getBankAccount() {
		return bankAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column to_trade_order.to_bank_account
	 *
	 * @param bankAccount
	 *            the value for to_trade_order.to_bank_account
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public void setBankAccount(String bankAccount) {
		this.bankAccount = bankAccount == null ? null : bankAccount.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column to_trade_order.to_payment_type
	 *
	 * @return the value of to_trade_order.to_payment_type
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public String getPaymentType() {
		return paymentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column to_trade_order.to_payment_type
	 *
	 * @param paymentType
	 *            the value for to_trade_order.to_payment_type
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public void setPaymentType(String paymentType) {
		this.paymentType = paymentType == null ? null : paymentType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column to_trade_order.to_create_date
	 *
	 * @return the value of to_trade_order.to_create_date
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column to_trade_order.to_create_date
	 *
	 * @param createDate
	 *            the value for to_trade_order.to_create_date
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column to_trade_order.to_create_user_id
	 *
	 * @return the value of to_trade_order.to_create_user_id
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public String getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column to_trade_order.to_create_user_id
	 *
	 * @param createUserId
	 *            the value for to_trade_order.to_create_user_id
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId == null ? null : createUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column to_trade_order.to_last_updated_date
	 *
	 * @return the value of to_trade_order.to_last_updated_date
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public Date getLastUpdatedDate() {
		return lastUpdatedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column to_trade_order.to_last_updated_date
	 *
	 * @param lastUpdatedDate
	 *            the value for to_trade_order.to_last_updated_date
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column to_trade_order.to_last_updated_user_id
	 *
	 * @return the value of to_trade_order.to_last_updated_user_id
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public String getLastUpdatedUserId() {
		return lastUpdatedUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column to_trade_order.to_last_updated_user_id
	 *
	 * @param lastUpdatedUserId
	 *            the value for to_trade_order.to_last_updated_user_id
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public void setLastUpdatedUserId(String lastUpdatedUserId) {
		this.lastUpdatedUserId = lastUpdatedUserId == null ? null : lastUpdatedUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column to_trade_order.to_is_valid
	 *
	 * @return the value of to_trade_order.to_is_valid
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public Boolean getIsValid() {
		return isValid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column to_trade_order.to_is_valid
	 *
	 * @param isValid
	 *            the value for to_trade_order.to_is_valid
	 *
	 * @mbggenerated Mon Sep 12 15:38:37 CST 2016
	 */
	public void setIsValid(Boolean isValid) {
		this.isValid = isValid;
	}
}