package com.codi.bus.core.domain;

import java.util.Date;

public class Transaction {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ts_transaction.ts_transaction_id
	 *
	 * @mbggenerated Fri Sep 09 17:16:56 CST 2016
	 */
	private Long transactionId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ts_transaction.ts_transaction_type
	 *
	 * @mbggenerated Fri Sep 09 17:16:56 CST 2016
	 */
	private String transactionType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ts_transaction.ts_transaction_api
	 *
	 * @mbggenerated Fri Sep 09 17:16:56 CST 2016
	 */
	private String transactionApi;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ts_transaction.ts_request_content
	 *
	 * @mbggenerated Fri Sep 09 17:16:56 CST 2016
	 */
	private String requestContent;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ts_transaction.ts_response_content
	 *
	 * @mbggenerated Fri Sep 09 17:16:56 CST 2016
	 */
	private String responseContent;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ts_transaction.ts_create_date
	 *
	 * @mbggenerated Fri Sep 09 17:16:56 CST 2016
	 */
	private Date createDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ts_transaction.ts_create_user_id
	 *
	 * @mbggenerated Fri Sep 09 17:16:56 CST 2016
	 */
	private String createUserId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ts_transaction.ts_last_updated_date
	 *
	 * @mbggenerated Fri Sep 09 17:16:56 CST 2016
	 */
	private Date lastUpdatedDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ts_transaction.ts_last_updated_user_id
	 *
	 * @mbggenerated Fri Sep 09 17:16:56 CST 2016
	 */
	private String lastUpdatedUserId;

	private Boolean isValid;

	public Boolean getIsValid() {
		return isValid;
	}

	public void setIsValid(Boolean isValid) {
		this.isValid = isValid;
	}

	private Integer transactionStatus;

	public Integer getTransactionStatus() {
		return transactionStatus;
	}

	public void setTransactionStatus(Integer transactionStatus) {
		this.transactionStatus = transactionStatus;
	}
	
	private Long orderId;

	public Long getOrderId() {
		return orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ts_transaction.ts_transaction_id
	 *
	 * @return the value of ts_transaction.ts_transaction_id
	 *
	 * @mbggenerated Fri Sep 09 17:16:56 CST 2016
	 */
	public Long getTransactionId() {
		return transactionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ts_transaction.ts_transaction_id
	 *
	 * @param tsTransactionId
	 *            the value for ts_transaction.ts_transaction_id
	 *
	 * @mbggenerated Fri Sep 09 17:16:56 CST 2016
	 */
	public void setTransactionId(Long transactionId) {
		this.transactionId = transactionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ts_transaction.ts_transaction_type
	 *
	 * @return the value of ts_transaction.ts_transaction_type
	 *
	 * @mbggenerated Fri Sep 09 17:16:56 CST 2016
	 */
	public String getTransactionType() {
		return transactionType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ts_transaction.ts_transaction_type
	 *
	 * @param tsTransactionType
	 *            the value for ts_transaction.ts_transaction_type
	 *
	 * @mbggenerated Fri Sep 09 17:16:56 CST 2016
	 */
	public void setTransactionType(String transactionType) {
		this.transactionType = transactionType == null ? null : transactionType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ts_transaction.ts_transaction_api
	 *
	 * @return the value of ts_transaction.ts_transaction_api
	 *
	 * @mbggenerated Fri Sep 09 17:16:56 CST 2016
	 */
	public String getTransactionApi() {
		return transactionApi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ts_transaction.ts_transaction_api
	 *
	 * @param tsTransactionApi
	 *            the value for ts_transaction.ts_transaction_api
	 *
	 * @mbggenerated Fri Sep 09 17:16:56 CST 2016
	 */
	public void setTransactionApi(String transactionApi) {
		this.transactionApi = transactionApi == null ? null : transactionApi.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ts_transaction.ts_request_content
	 *
	 * @return the value of ts_transaction.ts_request_content
	 *
	 * @mbggenerated Fri Sep 09 17:16:56 CST 2016
	 */
	public String getRequestContent() {
		return requestContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ts_transaction.ts_request_content
	 *
	 * @param requestContent
	 *            the value for ts_transaction.ts_request_content
	 *
	 * @mbggenerated Fri Sep 09 17:16:56 CST 2016
	 */
	public void setRequestContent(String requestContent) {
		this.requestContent = requestContent == null ? null : requestContent.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ts_transaction.ts_response_content
	 *
	 * @return the value of ts_transaction.ts_response_content
	 *
	 * @mbggenerated Fri Sep 09 17:16:56 CST 2016
	 */
	public String getResponseContent() {
		return responseContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ts_transaction.ts_response_content
	 *
	 * @param responseContent
	 *            the value for ts_transaction.ts_response_content
	 *
	 * @mbggenerated Fri Sep 09 17:16:56 CST 2016
	 */
	public void setResponseContent(String responseContent) {
		this.responseContent = responseContent == null ? null : responseContent.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ts_transaction.ts_create_date
	 *
	 * @return the value of ts_transaction.ts_create_date
	 *
	 * @mbggenerated Fri Sep 09 17:16:56 CST 2016
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ts_transaction.ts_create_date
	 *
	 * @param createDate
	 *            the value for ts_transaction.ts_create_date
	 *
	 * @mbggenerated Fri Sep 09 17:16:56 CST 2016
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ts_transaction.ts_create_user_id
	 *
	 * @return the value of ts_transaction.ts_create_user_id
	 *
	 * @mbggenerated Fri Sep 09 17:16:56 CST 2016
	 */
	public String getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ts_transaction.ts_create_user_id
	 *
	 * @param createUserId
	 *            the value for ts_transaction.ts_create_user_id
	 *
	 * @mbggenerated Fri Sep 09 17:16:56 CST 2016
	 */
	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId == null ? null : createUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ts_transaction.ts_last_updated_date
	 *
	 * @return the value of ts_transaction.ts_last_updated_date
	 *
	 * @mbggenerated Fri Sep 09 17:16:56 CST 2016
	 */
	public Date getLastUpdatedDate() {
		return lastUpdatedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ts_transaction.ts_last_updated_date
	 *
	 * @param lastUpdatedDate
	 *            the value for ts_transaction.ts_last_updated_date
	 *
	 * @mbggenerated Fri Sep 09 17:16:56 CST 2016
	 */
	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ts_transaction.ts_last_updated_user_id
	 *
	 * @return the value of ts_transaction.ts_last_updated_user_id
	 *
	 * @mbggenerated Fri Sep 09 17:16:56 CST 2016
	 */
	public String getLastUpdatedUserId() {
		return lastUpdatedUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ts_transaction.ts_last_updated_user_id
	 *
	 * @param lastUpdatedUserId
	 *            the value for ts_transaction.ts_last_updated_user_id
	 *
	 * @mbggenerated Fri Sep 09 17:16:56 CST 2016
	 */
	public void setLastUpdatedUserId(String lastUpdatedUserId) {
		this.lastUpdatedUserId = lastUpdatedUserId == null ? null : lastUpdatedUserId.trim();
	}
}