package com.codi.bus.core.domain;

import java.util.Date;

public class User {
	
	public static final Integer USER_STATE_MOBILE = 1;	
	public static final Integer USER_STATE_BANK = 2;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ur_user.ur_user_id
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	private Long userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ur_user.ur_user_mobile
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	private String userMobile;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ur_user.ur_user_name
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	private String userName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ur_user.ur_user_card
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	private String userCard;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ur_user.ur_user_email
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	private String userEmail;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ur_user.ur_login_password
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	private String loginPassword;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ur_user.ur_trade_password
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	private String tradePassword;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ur_user.ur_user_state
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	private Integer userState;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ur_user.ur_create_date
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	private Date createDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ur_user.ur_create_user_id
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	private String createUserId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ur_user.ur_last_updated_date
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	private Date lastUpdatedDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ur_user.ur_last_updated_user_id
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	private String lastUpdatedUserId;

	private String authCode;

	public String getAuthCode() {
		return authCode;
	}

	public void setAuthCode(String authCode) {
		this.authCode = authCode;
	}

	private Boolean isValid;

	public Boolean getIsValid() {
		return isValid;
	}

	public void setIsValid(Boolean isValid) {
		this.isValid = isValid;
	}

	private String externalClientId;

	public String getExternalClientId() {
		return externalClientId;
	}

	public void setExternalClientId(String externalClientId) {
		this.externalClientId = externalClientId;
	}
	
	//标志用户从哪里注册的
	private String userFrom;

	public String getUserFrom() {
		return userFrom;
	}

	public void setUserFrom(String userFrom) {
		this.userFrom = userFrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ur_user.ur_user_id
	 *
	 * @return the value of ur_user.ur_user_id
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ur_user.ur_user_id
	 *
	 * @param urUserId
	 *            the value for ur_user.ur_user_id
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ur_user.ur_user_mobile
	 *
	 * @return the value of ur_user.ur_user_mobile
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	public String getUserMobile() {
		return userMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ur_user.ur_user_mobile
	 *
	 * @param urUserMobile
	 *            the value for ur_user.ur_user_mobile
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	public void setUserMobile(String userMobile) {
		this.userMobile = userMobile == null ? null : userMobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ur_user.ur_user_name
	 *
	 * @return the value of ur_user.ur_user_name
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ur_user.ur_user_name
	 *
	 * @param urUserName
	 *            the value for ur_user.ur_user_name
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ur_user.ur_user_card
	 *
	 * @return the value of ur_user.ur_user_card
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	public String getUserCard() {
		return userCard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ur_user.ur_user_card
	 *
	 * @param urUserCard
	 *            the value for ur_user.ur_user_card
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	public void setUserCard(String userCard) {
		this.userCard = userCard == null ? null : userCard.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ur_user.ur_user_email
	 *
	 * @return the value of ur_user.ur_user_email
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	public String getUserEmail() {
		return userEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ur_user.ur_user_email
	 *
	 * @param urUserEmail
	 *            the value for ur_user.ur_user_email
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail == null ? null : userEmail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ur_user.ur_login_password
	 *
	 * @return the value of ur_user.ur_login_password
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	public String getLoginPassword() {
		return loginPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ur_user.ur_login_password
	 *
	 * @param urLoginPassword
	 *            the value for ur_user.ur_login_password
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	public void setLoginPassword(String loginPassword) {
		this.loginPassword = loginPassword == null ? null : loginPassword.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ur_user.ur_trade_password
	 *
	 * @return the value of ur_user.ur_trade_password
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	public String getTradePassword() {
		return tradePassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ur_user.ur_trade_password
	 *
	 * @param urTradePassword
	 *            the value for ur_user.ur_trade_password
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	public void setTradePassword(String tradePassword) {
		this.tradePassword = tradePassword == null ? null : tradePassword.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ur_user.ur_user_state
	 *
	 * @return the value of ur_user.ur_user_state
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	public Integer getUserState() {
		return userState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ur_user.ur_user_state
	 *
	 * @param urUserState
	 *            the value for ur_user.ur_user_state
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	public void setUserState(Integer userState) {
		this.userState = userState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ur_user.ur_create_date
	 *
	 * @return the value of ur_user.ur_create_date
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ur_user.ur_create_date
	 *
	 * @param urCreateDate
	 *            the value for ur_user.ur_create_date
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ur_user.ur_create_user_id
	 *
	 * @return the value of ur_user.ur_create_user_id
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	public String getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ur_user.ur_create_user_id
	 *
	 * @param urCreateUserId
	 *            the value for ur_user.ur_create_user_id
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ur_user.ur_last_updated_date
	 *
	 * @return the value of ur_user.ur_last_updated_date
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	public Date getLastUpdatedDate() {
		return lastUpdatedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ur_user.ur_last_updated_date
	 *
	 * @param urLastUpdatedDate
	 *            the value for ur_user.ur_last_updated_date
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ur_user.ur_last_updated_user_id
	 *
	 * @return the value of ur_user.ur_last_updated_user_id
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	public String getLastUpdatedUserId() {
		return lastUpdatedUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ur_user.ur_last_updated_user_id
	 *
	 * @param urLastUpdatedUserId
	 *            the value for ur_user.ur_last_updated_user_id
	 *
	 * @mbggenerated Thu Aug 18 14:52:53 CST 2016
	 */
	public void setLastUpdatedUserId(String lastUpdatedUserId) {
		this.lastUpdatedUserId = lastUpdatedUserId;
	}
}