package com.codi.bus.core.domain;

import java.util.Date;

public class Verify {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vf_verify.vf_verify_id
     *
     * @mbggenerated Tue Aug 23 11:03:50 CST 2016
     */
    private Long verifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vf_verify.vf_biz_code
     *
     * @mbggenerated Tue Aug 23 11:03:50 CST 2016
     */
    private String bizCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vf_verify.vf_mobile
     *
     * @mbggenerated Tue Aug 23 11:03:50 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vf_verify.vf_verify_code
     *
     * @mbggenerated Tue Aug 23 11:03:50 CST 2016
     */
    private String verifyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vf_verify.vf_create_date
     *
     * @mbggenerated Tue Aug 23 11:03:50 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vf_verify.vf_expire_date
     *
     * @mbggenerated Tue Aug 23 11:03:50 CST 2016
     */
    private Date expireDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vf_verify.vf_verify_id
     *
     * @return the value of vf_verify.vf_verify_id
     *
     * @mbggenerated Tue Aug 23 11:03:50 CST 2016
     */
    public Long getVerifyId() {
        return verifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vf_verify.vf_verify_id
     *
     * @param vfVerifyId the value for vf_verify.vf_verify_id
     *
     * @mbggenerated Tue Aug 23 11:03:50 CST 2016
     */
    public void setVerifyId(Long verifyId) {
        this.verifyId = verifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vf_verify.vf_biz_code
     *
     * @return the value of vf_verify.vf_biz_code
     *
     * @mbggenerated Tue Aug 23 11:03:50 CST 2016
     */
    public String getBizCode() {
        return bizCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vf_verify.vf_biz_code
     *
     * @param vfBizCode the value for vf_verify.vf_biz_code
     *
     * @mbggenerated Tue Aug 23 11:03:50 CST 2016
     */
    public void setBizCode(String bizCode) {
        this.bizCode = bizCode == null ? null : bizCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vf_verify.vf_mobile
     *
     * @return the value of vf_verify.vf_mobile
     *
     * @mbggenerated Tue Aug 23 11:03:50 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vf_verify.vf_mobile
     *
     * @param vfMobile the value for vf_verify.vf_mobile
     *
     * @mbggenerated Tue Aug 23 11:03:50 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vf_verify.vf_verify_code
     *
     * @return the value of vf_verify.vf_verify_code
     *
     * @mbggenerated Tue Aug 23 11:03:50 CST 2016
     */
    public String getVerifyCode() {
        return verifyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vf_verify.vf_verify_code
     *
     * @param vfVerifyCode the value for vf_verify.vf_verify_code
     *
     * @mbggenerated Tue Aug 23 11:03:50 CST 2016
     */
    public void setVerifyCode(String verifyCode) {
        this.verifyCode = verifyCode == null ? null : verifyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vf_verify.vf_create_date
     *
     * @return the value of vf_verify.vf_create_date
     *
     * @mbggenerated Tue Aug 23 11:03:50 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vf_verify.vf_create_date
     *
     * @param vfCreateDate the value for vf_verify.vf_create_date
     *
     * @mbggenerated Tue Aug 23 11:03:50 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vf_verify.vf_expire_date
     *
     * @return the value of vf_verify.vf_expire_date
     *
     * @mbggenerated Tue Aug 23 11:03:50 CST 2016
     */
    public Date getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vf_verify.vf_expire_date
     *
     * @param vfExpireDate the value for vf_verify.vf_expire_date
     *
     * @mbggenerated Tue Aug 23 11:03:50 CST 2016
     */
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }
}