package com.codi.bus.core.dao;

import com.codi.base.dao.BaseDAO;
import com.codi.bus.core.domain.AppVersionInfo;

public interface AppVersionInfoDao extends BaseDAO<AppVersionInfo> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_version_info
     *
     * @mbggenerated Tue Oct 18 16:11:30 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_version_info
     *
     * @mbggenerated Tue Oct 18 16:11:30 CST 2016
     */
    int insert(AppVersionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_version_info
     *
     * @mbggenerated Tue Oct 18 16:11:30 CST 2016
     */
    int insertSelective(AppVersionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_version_info
     *
     * @mbggenerated Tue Oct 18 16:11:30 CST 2016
     */
    AppVersionInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_version_info
     *
     * @mbggenerated Tue Oct 18 16:11:30 CST 2016
     */
    int updateByPrimaryKeySelective(AppVersionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_version_info
     *
     * @mbggenerated Tue Oct 18 16:11:30 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(AppVersionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_version_info
     *
     * @mbggenerated Tue Oct 18 16:11:30 CST 2016
     */
    int updateByPrimaryKey(AppVersionInfo record);
}