INSERT INTO `SYS_BANNER` (NAME, IMG_URL, BANNER_ORDER, CREATE_DATE, UPDATE_DATE, DESCRIPTION)
VALUES ('Revision', 'http://file.cd121.com/banner750X3800.png', 20,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP, '科地基金全面改版');
